### ISSUE TITLE
Glitch in acme when enlarging a window in less than font->height

### ISSUE THREAD

**Issue by jroimartin** [9fans/plan9port#10]
In acme, if you enlarge a window in less than font->height its body is not redrawn correctly, duplicating the old text present at that position. The following images show this behaviour:

Before resizing:
![screen shot 2014-12-03 at 23 55 50](https://cloud.githubusercontent.com/assets/1223476/5290614/b632ab44-7b48-11e4-96fd-046db6778e4b.png)

After resizing:
![screen shot 2014-12-03 at 23 55 03](https://cloud.githubusercontent.com/assets/1223476/5290626/d108f82e-7b48-11e4-804b-bef2f8583201.png)

**Comment by echosa** [comment]
I'm having similar glitches. I haven't narrowed the cause, and I can usually fix it by simply resizing a window a bit. I thought it might be an issue with retina displays on MacBook Pros, but that's purely a guess.

**Comment by bhuntsman** [comment]
Is this still an issue?  I can't seem to reproduce it with the current version.

**Comment by dancrossnyc** [comment]
@rsc any thoughts here?

**Comment by bladedvox** [comment]
Been using the my patch for a while now and it seems to work well with no ill effects. Will open a PR :heart:
