### ISSUE TITLE
pdos.lcs.mit.edu/~rsc/ moved to HTTPS

### ISSUE THREAD

**Issue by sviscapi** [9fans/plan9port#101]
Hi all,

Tiny bug report: downloading dictionaries and sky databases from pdos.lcs.mit.edu/~@rsc no longer works, because the site moved to HTTPS. As a result, hget fails because there's no TLS client, and wget has to be used with the "--no-check-certificate" option, at least on my system.

Cheers, Sam a.k.a "Magic Sam" from the Open Pandora community

Release thread: https://pyra-handheld.com/boards/threads/plan-9-from-user-space.65064/
Package on official repository: http://repo.openpandora.org/?page=detail&app=plan9port-magicsam

**Comment by 0intro** [comment]
We finally moved the website to [9fans.github.io](https://9fans.github.io/). These file are now available at [pgw.tar.bz2](https://9fans.github.io/plan9port/dist/pgw.tar.bz2),  [roget.tar.bz2](https://9fans.github.io/plan9port/dist/roget.tar.bz2) and  [scat.tar.bz2](https://9fans.github.io/plan9port/dist/scat.tar.bz2). I've updated the various README accordingly.

Thanks!
