### ISSUE TITLE
vac and trees containing device files

### ISSUE THREAD

**Issue by stroucki** [9fans/plan9port#103]
I use vac for backups on Linux. One of my partitions contains device files, and vac gets blocked trying to open "irlpt1" (c 161 17) in ./src/lib9/_p9dir.c:234 to obtain its "disk size". When testing this issue, my system rebooted because vac apparently triggered the watchdog service.

Is obtaining the disk size really necessary? Some platforms directly return 0 for their implementation of the disksize function. For safety and functionality, I suggest that the code should not attempt to open device files like this.

**Comment by rsc** [comment]
Sorry, but plan9port ls -l working on disk devices is one of my favorite plan9port features.
It seems like it might be OK to avoid opening character devices.
