### ISSUE TITLE
bin/web support to chromium in FreeBSD 11

### ISSUE THREAD

**Issue by drocha87** [9fans/plan9port#108]
faced a problem trying open url's in acme using FreeBSD 11.1 with chromium.
The issue is that chromium is located in /usr/local/bin as chrome. 
Set $BROWSER to chrome do not fit all the possible cases in bin/web. 
I did a change to bin/web to fit chromium as well 

```
diff --git a/bin/web b/bin/web
index 8c6fdd4d..1f1f5bd8 100755
--- a/bin/web
+++ b/bin/web
@@ -37,6 +37,9 @@ plumbunix()
         *google-chrome*|*chromium*)
                 $BROWSER "$@"
                 ;;
+       *)
+               $BROWSER "$@"
+               ;;
        esac
  }
```

I don't think this is the best approach but work just fine!

Sorry for my poor english!

**Comment by 0intro** [comment]
Does this change works in your case?

```
--- a/bin/web
+++ b/bin/web
@@ -34,7 +34,7 @@ plumbunix()
 		$BROWSER -remote 'openURL('"$@"',new-tab)' ||
 		$BROWSER "$@"
 		;;
-	*google-chrome*|*chromium*)
+	*google-chrome*|*chromium*|*chrome*)
 		$BROWSER "$@"
 		;;
 	esac
```

If so, I'll submit this change.

**Comment by drocha87** [comment]
Worked just fine. 

Thanks for the reply!

**Comment by 0intro** [comment]
I've pushed commit 67d25b6fb0ec561de501f2df969c9cad999672d0. Thanks.
