### ISSUE TITLE
no upas/fs

### ISSUE THREAD

**Issue by keks** [9fans/plan9port#113]
I'm not sure whether this currently beyond the scope of p9p, but [cat-v claims] it works. What's needed to fix this?

[cat-v claims]: http://doc.cat-v.org/bell_labs/upas_mail_system/

**Comment by 0intro** [comment]
There is an incomplete port of [upas/fs](https://github.com/9fans/plan9port/tree/master/src/cmd/upas/fs), but there is also [upas/nfs](https://github.com/9fans/plan9port/tree/master/src/cmd/upas/nfs) (installed as `mailfs`) which is a reimplementation of [upas/fs](https://github.com/9fans/plan9port/tree/master/src/cmd/upas/fs) by Russ Cox. The [upas/nfs](https://github.com/9fans/plan9port/tree/master/src/cmd/upas/nfs) file system is slightly different. It only supports imap so far.

**Comment by keks** [comment]
Thank you! I was just about to post that upas/fs wouldn't build.

**Comment by keks** [comment]
Does that mean that smtp also doesn't work?
