### ISSUE TITLE
Some box drawing characters not shown on macOS using certain fonts

### ISSUE THREAD

**Issue by jxy** [9fans/plan9port#120]
Here on High Sierra, using Go Mono font distributed with texlive 2017.

``font=/mnt/font/GoMono/24a/font sam tmp/box_unicode``

<img width="1072" alt="screen shot 2017-10-25 at 1 35 37 pm" src="https://user-images.githubusercontent.com/89739/32016487-bdd9dfde-b989-11e7-9f2b-49a65b779bbf.png">

Some of the glyphs, namely, 2518, 251C, and 253C, are not displayed.  I checked that Go Mono does come with these.

Here is the contents of the file shown in sam above.
```
       0 1 2 3 4 5 6 7 8 9 A B C D E F
U+250x ─ ━ │ ┃ ┄ ┅ ┆ ┇ ┈ ┉ ┊ ┋ ┌ ┍ ┎ ┏
U+251x ┐ ┑ ┒ ┓ └ ┕ ┖ ┗ ┘ ┙ ┚ ┛ ├ ┝ ┞ ┟
U+252x ┠ ┡ ┢ ┣ ┤ ┥ ┦ ┧ ┨ ┩ ┪ ┫ ┬ ┭ ┮ ┯
U+253x ┰ ┱ ┲ ┳ ┴ ┵ ┶ ┷ ┸ ┹ ┺ ┻ ┼ ┽ ┾ ┿
U+254x ╀ ╁ ╂ ╃ ╄ ╅ ╆ ╇ ╈ ╉ ╊ ╋ ╌ ╍ ╎ ╏
U+255x ═ ║ ╒ ╓ ╔ ╕ ╖ ╗ ╘ ╙ ╚ ╛ ╜ ╝ ╞ ╟
U+256x ╠ ╡ ╢ ╣ ╤ ╥ ╦ ╧ ╨ ╩ ╪ ╫ ╬ ╭ ╮ ╯
U+257x ╰ ╱ ╲ ╳ ╴ ╵ ╶ ╷ ╸ ╹ ╺ ╻ ╼ ╽ ╾ ╿
```

**Comment by rsc** [comment]
FontBook suggests that Go Mono does not in fact come with those glyphs. So fontsrv is using whatever Apple defaults to as fallback, and it looks like some of the choices work better than others.

![screen shot 2017-10-25 at 3 07 00 pm](https://user-images.githubusercontent.com/104030/32017937-4258c7e6-b996-11e7-9b44-8fc0fb080126.png)

**Comment by rsc** [comment]
Never mind the last comment. I see that you are asking specifically for 2518 251C and 253C. FontBook clearly confirms those are present, and I agree that sam is not showing them correctly.
