### ISSUE TITLE
Install problem: fatal error: fontconfig/fontconfig.h: No such file or directory

### ISSUE THREAD

**Issue by flyq** [9fans/plan9port#128]
Env: 
Ubuntu16.04 installed in VMware Workstation 14 Pro 14.0.0 build-6661328

flyq@ubuntu-zh:/usr/local/plan9$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

install steps:
git clone https://github.com/9fans/plan9port.git
sudo mv plan9port/ /usr/local/plan9
cd /usr/local/plan9
./INSTALL

information:
+ Mailing list: https://groups.google.com/group/plan9port-dev
+ Issue tracker: https://github.com/9fans/plan9port/issues/
+ Submitting changes: https://github.com/9fans/plan9port/pulls
 
* Resetting /usr/local/plan9/config
* Compiler version:
	gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) 
* Running on Linux: checking for NPTL...
	NPTL found.
	fontsrv dependencies not found.
* Building mk...
>>> pwd
>>> cd /usr/local/plan9/src/lib9
9c dirread.c
   fchdir(oldwd);
   ^
  fchdir(oldwd);
  ^
>>> cd /usr/local/plan9/src/lib9
9c readcons.c
     write(fd, "\n", 1);
     ^
     write(fd, "\n", 1);
     ^
>>> pwd
>>> pwd
>>> pwd
* Building everything (be patient)...
>>> cd /usr/local/plan9/src/lib9; mk all                  
9c  dirread.c
   fchdir(oldwd);
   ^
  fchdir(oldwd);
  ^
>>> cd /usr/local/plan9/src/lib9; mk all
9c  readcons.c
     write(fd, "\n", 1);
     ^
     write(fd, "\n", 1);
     ^
>>> cd /usr/local/plan9/src/libthread; mk all 
9c -o exec.o  -I. exec.c
    chdir(dir); /* best effort */
    ^
>>> cd /usr/local/plan9/src/cmd; mk all  
9c  dd.c
   read(ibf, ibuf, ibs);
   ^
>>> cd /usr/local/plan9/src/cmd; mk all
9c  fortune.c
   read(ix, off, sizeof(off));
   ^
>>> cd /usr/local/plan9/src/cmd; mk all
9c  tar.c
   chdir(origdir);  /* for correctness & profiling */
   ^
>>> cd /usr/local/plan9/src/cmd/9660; mk all
9c  unix.c
  ftruncate(fd, size);
  ^
>>> cd /usr/local/plan9/src/cmd/9pfuse; mk all
9c  fuse.c
  writev(fusefd, vec, nvec);
  ^
>>> cd /usr/local/plan9/src/cmd/db; mk all        
9c  trcrun.c
   read(0, buf, 100);
   ^
>>> cd /usr/local/plan9/src/cmd/eqn; mk all 
9c  input.c
   fgets(ebuf, sizeof ebuf, curfile->fin);
   ^
>>> cd /usr/local/plan9/src/cmd/fontsrv; mk all
9c -I/usr/include -I/usr/include/freetype2 x11.c
x11.c:3:35: fatal error: fontconfig/fontconfig.h: No such file or directory
compilation terminated.
mk: 9c -I/usr/include -I/usr/include/freetype2 x11.c  : exit status=exit(1)
mk: for i in ...  : exit status=exit(1)
mk: for i in ...  : exit status=exit(1)

I run:
flyq@ubuntu-zh:/usr/local/plan9$ apt-file search fontconfig/fontconfig.h

emscripten: /usr/share/emscripten/tests/poppler/fontconfig/fontconfig.h
libfontconfig1-dev: /usr/include/fontconfig/fontconfig.h

but under /usr/share/ there are no emscripten folder.
under /usr/include/ there are no fontconfig folder.

I don't know where to get the fontconfig.h

**Comment by 0intro** [comment]
You have to install fontconfig. On Ubuntu, fontconfig.h should be in the libfontconfig1-dev package.

**Comment by flyq** [comment]
Thanks a lot for you help.
I just solved the problems.

Steps:
1. run _sudo apt-get install libfontconfig1-dev_
2. run _./INSTALL_
3. There are some other package can't find, so run _apt-file search ****/***.h_, 
etc: 
event.c:9:34: fatal error: X11/extensions/shape.h: No such file or directory
and run _apt-file search X11/extensions/shape.h_
logout is: libxext-dev: /usr/include/X11/extensions/shape.h
4. run _sudo apt-get install libxext-dev_
5. run _./INSATLL_ , if not success, back to step 3 until the logout is:
...
>>> cd /usr/local/plan9/src/cmd/grap; mk -k install
9c  main.c
  mkstemp(tempfile);
  ^
>>> cd /usr/local/plan9/src/cmd/tpic; mk -k install    
9c  input.c
  fgets(ebuf, sizeof ebuf, curfile->fin);
  ^
  system(shellbuf);
  ^
* Cleaning up...                              
* Renaming hard-coded /usr/local/plan9 paths...           
* Building web manual...
* Done.                          
	
* Add these to your profile environment.
	PLAN9=/usr/local/plan9 export PLAN9
	PATH=$PATH:$PLAN9/bin export PATH
