### ISSUE TITLE
system problems

### ISSUE THREAD

**Issue by flyq** [9fans/plan9port#129]
After I installed the plan 9, [Install problem: fatal error: fontconfig/fontconfig.h: No such file or directory](https://github.com/9fans/plan9port/issues/128)
the command 'ls' can't work.

`flyq@ubuntu-zh:~$ ls
usage: ls [-dlmnpqrstuFQ] [file ...]
`
but sudo ls is work well, maybe I need set the env like bashrc or etc.

**Comment by 0intro** [comment]
This is probably happening because you set $PLAN9/bin at the beginning of your PATH so plan9port's ls get executed instead of your system's ls and doesn't support the options passed with an alias.

You have to put $PLAN9/bin at the end of your PATH.

**Comment by flyq** [comment]
Thanks a lot.

Follow your advice:
I edit the ~/.bashrc

before:
`export PLAN9=/usr/local/plan9`
`export PATH=$PLAN9/bin:$PATH`

now:
`export PLAN9=/usr/local/plan9`
`export PATH=$PATH:$PLAN9/bin`

`source .bashrc` or restart OS

and everything is ok.
