### ISSUE TITLE
acme -a does nothing

### ISSUE THREAD

**Issue by raingloom** [9fans/plan9port#137]
I usually open it as `acme -a &; disown` and it does not actually turn auto-indent on.

`Indent ON` works fine.

**Comment by rsc** [comment]
`acme -a` executes literally the same one line of code as Indent ON. It's working fine for me. I'm not sure what is causing problems on your end.

**Comment by raingloom** [comment]
Grah! Nevermind, I had a wrapper script that I forgot about `>_<`

It wasn't passing parameters on correctly.
