### ISSUE TITLE
macOS version of fontsrv squashes some subfont images

### ISSUE THREAD

**Issue by lufia** [9fans/plan9port#146]
In macOS, `fontsrv` squashes some subfonts.
Particularly a full width character with **GoMono** font draws only left side of the subfont image.

Attached *x30a0.png* file has created with command:

```console
$ fontsrv -p GoMono/22a/x30a0.bit | topng >x30a0.png
```

![x30a0](https://user-images.githubusercontent.com/1784379/36310103-5238b6ac-136a-11e8-9494-dd986c2796fb.png)

And also I experimentally modified `mksubfont()` in *src/cmd/fontsrv/osx.c*:

```c
        bbox = CTFontGetBoundingBox(font);
-       x = (int)(bbox.size.width + 0.99999999);
+       x = (int)(bbox.size.width + 0.99999999)*2;
```

Attached *x30a0-2.png* has created with patched version of `fontsrv`.

![x30a0-2](https://user-images.githubusercontent.com/1784379/36310101-5212348c-136a-11e8-8f22-71b369c388b9.png)

Perhaps related issues:

* #18
* #120

**Comment by jxy** [comment]
Looks like a bug in CTFontGetBoundingBox, which apparently only returns the bounding box of latin letters?  This change also solves #120 too.
