### ISSUE TITLE
OpenBSD: "Abort trap"

### ISSUE THREAD

**Issue by rennis250** [9fans/plan9port#148]
Almost every Plan9 binary I have tried doesn't work on OpenBSD -current, regardless of whether it is installed from source or from the packages. The binaries fail with the following error:

"Abort trap"

The only binary that worked was Rio.

**Comment by mischief** [comment]
this should be fixed by https://marc.info/?l=openbsd-ports&m=152070731218921&w=2

**Comment by rennis250** [comment]
Thanks. I noticed that a day later, but forgot to update here. It is indeed working correctly again. :)
