### ISSUE TITLE
sam font very small on macOS

### ISSUE THREAD

**Issue by nicoNaN** [9fans/plan9port#149]
On macOS 10.3.3, sam's font size is extremely small. Could this be a DPI issue?

The man page for sam doesn't mention specifying a font via fontsrv, as in acme.

<img width="1072" alt="screen shot 2018-03-14 at 10 39 06 am" src="https://user-images.githubusercontent.com/7397825/37409211-26792182-2774-11e8-9070-58f103338458.png">

**Comment by rsc** [comment]
What is your $font? Does acme work? Sam should work as well as acme does.

**Comment by nicoNaN** [comment]
Thanks for the reply - you're right, doing `font=/mnt/font/SFMono-Regular/12a/font sam` works great. Did not think to try environment variables!
