### ISSUE TITLE
cannot build/install on Ubuntu bionic

### ISSUE THREAD

**Issue by arseniuss** [9fans/plan9port#168]
After installing needed packages, installation still fails on:
> ...
> cd /usr/local/plan9/src/cmd/devdraw; mk all
> 9l -o o.devdraw devdraw.o latin1.o mouseswap.o winsize.o x11-alloc.o x11-cload.o x11-draw.o x11-fill.o x11-get.o x11-init.o x11-itrans.o x11-keysym2ucs.o x11-load.o x11-pixelbits.o x11-srv.o x11-unload.o x11-wsys.o 
> /usr/local/plan9/src/cmd/devdraw/devdraw.c:565: undefined reference to `memlfree'
> /usr/local/plan9/src/cmd/devdraw/devdraw.c:563: undefined reference to `memldelete'
> /usr/local/plan9/src/cmd/devdraw/devdraw.c:1167: undefined reference to `memline'
> /usr/local/plan9/src/cmd/devdraw/devdraw.c:1136: undefined reference to `memdraw'
> /usr/local/plan9/src/cmd/devdraw/devdraw.c:1263: undefined reference to `memlorigin'
> /usr/local/plan9/src/cmd/devdraw/devdraw.c:1390: undefined reference to `memunload'
> /usr/local/plan9/src/cmd/devdraw/devdraw.c:844: undefined reference to `memlalloc'
> /usr/local/plan9/src/cmd/devdraw/devdraw.c:867: undefined reference to `memlsetrefresh'
> /usr/local/plan9/src/cmd/devdraw/devdraw.c:708: undefined reference to `memdraw'
> /usr/local/plan9/src/cmd/devdraw/devdraw.c:937: undefined reference to `memdraw'
> /usr/local/plan9/src/cmd/devdraw/devdraw.c:1553: undefined reference to `memload'
> /usr/local/plan9/src/cmd/devdraw/devdraw.c:1522: undefined reference to `memltofrontn'
> /usr/local/plan9/src/cmd/devdraw/devdraw.c:1450: undefined reference to `memdraw'
> /usr/local/plan9/src/cmd/devdraw/devdraw.c:835: undefined reference to `memlnorefresh'
> /usr/local/plan9/src/cmd/devdraw/devdraw.c:1524: undefined reference to `memltorearn'
> /usr/local/plan9/src/cmd/devdraw/devdraw.c:851: undefined reference to `memldelete'
> /usr/local/plan9/src/libmemdraw/arc.c:110: undefined reference to `memdraw'
> /usr/local/plan9/src/libmemdraw/ellipse.c:229: undefined reference to `memdraw'
> /usr/local/plan9/src/libmemdraw/ellipse.c:213: undefined reference to `memdraw'
> /usr/local/plan9/src/libmemdraw/fillpoly.c:53: undefined reference to `memdraw'
> /usr/local/plan9/src/libmemdraw/fillpoly.c:67: undefined reference to `memdraw'
> /usr/local/plan9/lib/libmemdraw.a(line.o):/usr/local/plan9/src/libmemdraw/line.c:278: more undefined references to `memdraw' follow
> /usr/local/plan9/src/libmemdraw/poly.c:21: undefined reference to `memline'
> collect2: error: ld returned 1 exit status
> mk: 9l -o o.devdraw ...  : exit status=exit(1)
> mk: for i in ...  : exit status=exit(1)
> mk: for i in ...  : exit status=exit(1)

uname -a: Linux nitro 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a: Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic

libx11-dev version 2:1.6.4-3
libxext-dev version 2:1.3.3-1
libxt-dev version 1:1.1.5-1

**Comment by 0intro** [comment]
I don't think it's related to a dependency issue. It seems devdraw is having trouble linking with libmemlayer.

Has libmemlayer been built successfully? Is $PLAN9/lib/libmemlayer.a existing?

**Comment by arseniuss** [comment]
$PLAN9/lib/libmemlayer.a exists.

**Comment by rsc** [comment]
I'm not sure how this could happen. If it is still happening please file a new bug.
