### ISSUE TITLE
fontsrv: imperfect font rendering at certain sizes

### ISSUE THREAD

**Issue by 4ad** [9fans/plan9port#18]
On OS X, some vector fonts are not rendered correctly at certain sizes. For example, this is 14p Lucida Grande with antialising, look at 'g', 'j', and 'y', but especially 'g':

![LG14anr](http://i.imgur.com/LNgqiUu.png)

This is on a retina display, it has the same problem but in real life it's much less visible:

![LG14ar](http://i.imgur.com/TLIRtAL.png)

The 15p Lucida Grande does not have this problem. Non retina:

![LG15anr](http://i.imgur.com/J0QcSND.png)

Retina:

![LG15ar](http://i.imgur.com/MCU3PXw.png)

This problem is not specific to Lucida Grande, in fact most fonts have some problem at some sizes. Unfortunately I couldn't find any Lucida font that rendered correctly at 14p or 13p, and 15p is too big for me. Some fonts are rendered worse than Lucida Grande though. This is Lucida Grande Light at 14p with antialising:

![LGL14anr](http://i.imgur.com/9VyjVKg.png)

And here is Lucida Grande Mono at 14p with antialising. Note the cut 'j':

![LGM14anr](http://i.imgur.com/XmPTuB0.png)

Some other fonts do work well at 14p. This is Anonymous Pro with antialising at 14p:

![AP14anr](http://i.imgur.com/GGvhyhd.png)

The 'g' is not cropped, though if you look in the tag you will see it touches the tag border.

If someone has an X11 server, it would be interesting to compare the results of the same fonts there too (different backend renderer).

**Comment by 4ad** [comment]
Ok, I tested on X11 too. Results are very interesting.

A picture makes a thousand words, so:

![1000words](http://i.imgur.com/Do16iyZ.png)

The font size is very different between X1, acme in OS X, and TextEdit in OS X. 10p in X11 is sized approximately like 14p in acme in OS X.

Note however, that the letter aspect ratio is different. X11 letters are less tall. The X11 letters are rendered correctly though. The problem with 'g' is not present in X11.

Font size in acme on OS X and TextEdit on OS X is almost the same but not quite.

**Comment by 4ad** [comment]
Same test but with Lucida Grande Mono:

![LGM](http://i.imgur.com/LE9aOiE.png)

**Comment by paulzhol** [comment]
the X11 code has the DPI hardcoded for 96, also hinting was disabled
recently.
I was toying with the prospect of rewriting it using pango, as freetype2
wasn't really fun last time..

**Comment by 4ad** [comment]
Using pango instead of freetype would be unfortunate, but I believe you when you say freetype is hard to work with.

	crimson:aram$ apt-rdepends --build-depends --follow=DEPENDS libpango-1.0-0
	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	libpango-1.0-0
	  Build-Depends: autotools-dev
	  Build-Depends: cdbs (>= 0.4.93)
	  Build-Depends: debhelper (>= 8.1.3)
	  Build-Depends: dh-autoreconf
	  Build-Depends: gnome-pkg-tools (>= 0.11)
	  Build-Depends: gobject-introspection (>= 0.9.12-4~)
	  Build-Depends: gtk-doc-tools (>= 1.15)
	  Build-Depends: libcairo2-dev (>= 1.12.10)
	  Build-Depends: libfontconfig1-dev (>= 2.10.91)
	  Build-Depends: libfreetype6-dev (>= 2.1.7)
	  Build-Depends: libgirepository1.0-dev (>= 0.9.5)
	  Build-Depends: libglib2.0-dev (>= 2.34.0)
	  Build-Depends: libharfbuzz-dev (>= 0.9.9)
	  Build-Depends: libthai-dev (>= 0.1.9)
	  Build-Depends: libx11-dev (>= 2:1.3.3-2)
	  Build-Depends: libxft-dev (>= 2.1.14-2)
	  Build-Depends: libxrender-dev (>= 1:0.9.0.2-2)
	  Build-Depends: libxt-dev
	  Build-Depends: perl
	  Build-Depends: pkg-config
	  Build-Depends-Indep: libglib2.0-doc
	crimson:aram$ apt-rdepends --build-depends --follow=DEPENDS freetype
	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	freetype
	  Build-Depends: autoconf
	  Build-Depends: automake
	  Build-Depends: bzip2
	  Build-Depends: debhelper (>= 8.9.4)
	  Build-Depends: docbook-to-man
	  Build-Depends: gettext (>= 0.10.36-2)
	  Build-Depends: libpng-dev
	  Build-Depends: libtool
	  Build-Depends: libx11-dev
	  Build-Depends: libz-dev
	  Build-Depends: quilt
	  Build-Depends: x11proto-core-dev
	crimson:aram$ 

Hardcoding DPI in X11 explains the different font size, so one mystery is solved. The others remain, however.

**Comment by paulzhol** [comment]
I don't remember that well, but I think X11 doesn't cut letters due to
https://github.com/9fans/plan9port/blob/master/src/cmd/fontsrv/x11.c#L83
and
https://github.com/9fans/plan9port/blob/master/src/cmd/fontsrv/x11.c#L132-L134
which I shamelesly took from the then OSX version.
