### ISSUE TITLE
Method to ignore colored prompts?

### ISSUE THREAD

**Issue by bbarker** [9fans/plan9port#180]
![image](https://user-images.githubusercontent.com/916366/45788074-656a5480-bc46-11e8-954d-3c1500e92e53.png)

Normally this looks like: `[nix-shell:~/workspace/TextTerra]$`, but green. My limited experience so far suggests any time coloring is attempted, this happens. Is there a convenient workaround? May programs change `PS1` without the user having much say in it. Even better might be to support color, but given the age of `acme` (I have fond memories of using it in high school half a life time ago), I suppose this is not an option.

**Comment by fhs** [comment]
The simplest fix is to set `$PS1` to something without color if `$termprog` is either `win` or `9term`.

**Comment by mkhl** [comment]
I think the proper way to fix this would be replacing the magic constants in your prompt with tput(1) invocations, which handles different terminal capabilities.

    PS1="$(tput setf 2)[the greenest prompt]\$$(tput setf 0) "

**Comment by bbarker** [comment]
Thanks for the suggestions; indeed these should work in the case I posted above and in similar cases. But some terminal applications are not proper UNIX shells (e.g., many build tools have interactive modes), so I'm not sure how I would set `PS1` in acme in this case (but maybe there is a way).

**Comment by rsc** [comment]
Typically you should set TERM=win or TERM=dumb in your environment. Any tool that continues to print escape sequences at that point is broken and should be fixed.

**Comment by 4ad** [comment]
Most tools behave properly when `TERM=dumb`, but git doesn't, at least for me. So I added this to `.gitconfig` to tame it:

    [color]
     	ui = never
