### ISSUE TITLE
Open programs in same window

### ISSUE THREAD

**Issue by detuma** [9fans/plan9port#184]
Hi, first question : is it possible to open programs in the current window like in plan 9 ? 
Second question : Does winwatch work in plan9port ?

**Comment by fhs** [comment]
It works fine for me. Where does it segfault?

**Comment by detuma** [comment]
Program received signal SIGSEGV, Segmentation fault.
0x000055555555abd0 in _string ()
(gdb) backtrace
#0  0x000055555555abd0 in _string ()
#1  0x0000555555556ca1 in drawwin (
    i=<optimized out>)
    at winwatch.c:185
#2  0x0000555555556ed5 in redraw (
    screen=<optimized out>, 
    all=all@entry=1)
    at winwatch.c:226
#3  0x0000555555557429 in p9main (
    argc=0, argv=<optimized out>)
    at winwatch.c:346
#4  0x0000555555556479 in main ()

**Comment by rsc** [comment]
Sorry, no, it's not possible to take over the window. The window system is just different from on Plan 9 (because it's not Plan 9). The best you could do would be to have the new window sit exactly on top of the old window but that seemed like too much bother.
