### ISSUE TITLE
suggestion: error window of cntrl+f to include the path where cntrl+f was executed?

### ISSUE THREAD

**Issue by dzklaim** [9fans/plan9port#187]
when executing cntrl+f and there is more than one alternative, acme creates a window labelled as +Errors (as usual). Then, the cursor is moved to that window so that we can comfortably search for the desired entry. It occurred to me that it might be convenient to open a file directly from this window, hence the suggestion :)

**Comment by fhs** [comment]
The disadvantage is that you end up with more window clutter instead of all completion output ending up in one window. Also note that the cursor moves to +Error window only the first time, when the +Error window is created.

**Comment by dzklaim** [comment]
that is correct. maybe it does not make much sense to change the behaviour. somehow I always close the window after completion :P so it would make sense for me. the way it works now it always feels unnatural to me, and usually involves too much mouse travel.

how do you do when you are checking a project with several folders and you just vaguely recollect some names and hierarchy structure? maybe a easier way is to create a keyboard shortcut to spawn a terminal an execute something like editinacme $(fzf).

**Comment by mkhl** [comment]
> how do you do when you are checking a project with several folders and you just vaguely recollect some names and hierarchy structure? maybe a easier way is to create a keyboard shortcut to spawn a terminal an execute something like `plumb -d edit $(fzf)`.

(At the risk of abusing the issue tracker, sorry:)
What I do is, in a window at the project root, Mouse-2 (run) `t remember` (which essentially runs `fzf --filter='remember'`), then Mouse-3 (look) the file I want in the resulting +Error window.

**Comment by dzklaim** [comment]
thanks :) I think that works reasonably well. for a quick opening the "terminal solution" might be faster but we loose the ability to "reuse text", which is one of my favorite acme features :)
