### ISSUE TITLE
Courier fonts missing?

### ISSUE THREAD

**Issue by bbarker** [9fans/plan9port#197]
I'm using `acme` to work on some things that really need monospace fonts. I noticed that courier is mentioned at https://9p.io/wiki/plan9/fonts/index.html but I can't find any courier fonts in plan9port. Are there any other monospace (bitmap?) fonts or directions on how to add fonts? 

My guess is that the courier fonts included in plan9 were the proprietary variants. Would it be possible to obtain these from a plan9 distribution?

**Comment by rsc** [comment]
Note that plan9port ships with monospace fonts. In acme all you need to do is exec Font to flip any particular window between monospace and variable-width fonts.

**Comment by rsc** [comment]
Specific fonts you can try include $PLAN9/font/{lucm,pelm,fixed}/*.font.
If you execute Font with an argument then you can try any particular font:

    Font /lib/font/bit/pelm/ascii.12.font

Also try 'fontsrv -p .' for a list of fonts that can be used courtesy of your host system.

**Comment by rsc** [comment]
Going to close this, since we're not going to add new fonts at this point.
