### ISSUE TITLE
fontsrv / devdraw: macOS 10.14 anti-aliased fonts are too heavy

### ISSUE THREAD

**Issue by jacobvosmaer** [9fans/plan9port#198]
![screenshot 2018-10-26 at 10 54 18](https://user-images.githubusercontent.com/1336311/47556007-999ff780-d90d-11e8-9efa-58fab7f96ab4.png)

I think this only happens on low-DPI screens, such as pre-Retina macbooks and external monitors. The fonts look fine on Retina. They also looked fine before, on macOS 10.13.

I don't know if the problem is in fontsrv or in devdraw.

**Comment by dzklaim** [comment]
Probably this helps

https://github.com/9fans/plan9port/pull/196

**Comment by jacobvosmaer** [comment]
I just found this command, which works:

```
defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO
```

I'll try the change from #196 too.

**Comment by jacobvosmaer** [comment]
Yes! #196 fixes this.

**Comment by rsc** [comment]
#196 merged.
