### ISSUE TITLE
Sending Ctrl-C ... to Acme Win

### ISSUE THREAD

**Issue by bennof** [9fans/plan9port#200]
Hi,

i like to use acme as my default editor and know have to develop software with javascript (npm) and Clojure. Is it possible to run a REPL in a WIN window (yes) but how can I send CRTL-C, CTRL-D and for Erlang CTRL-G sqeuences to that processes.

Thanks.
Benno

**Comment by jxy** [comment]
What happens when you type these control sequences normally?  It should work by default.

**Comment by bennof** [comment]
I get an undefined char box, caret and  questionmark or just the undefined char box.

**Comment by rsc** [comment]
If you type DEL (Fn+Delete(aka Backspace) on macOS) then it should go through immediately. Otherwise typed characters don't go through until you hit enter. Win always buffers until end of line so that you can retype.
