### ISSUE TITLE
devdraw: Ctrl-H should send Ctrl-H on macOS Metal

### ISSUE THREAD

**Issue by lufia** [9fans/plan9port#204]
I use `acme` on macOS at ad2d49503b1242be501ab92832400ef344a6afae (#194).

In this revision, Ctrl-H key inserts 0x7f(DEL) at cursor on screen such as acme or 9term.
Below image is a result that I type "hello^h^h^h" on new window.
<img width="179" alt="ctrl-h" src="https://user-images.githubusercontent.com/1784379/48602055-3f96cd00-e9b5-11e8-96f3-59092bf39e4c.png">

Is this expected behavior?

**Comment by jxy** [comment]
I think I swapped bs and del, so that delete key generates bs and control-h generates del.  If it's not desirable, we can delete one line in the file.

**Comment by rsc** [comment]
Yes, please update devdraw to send Ctrl-H when Ctrl-H is typed, thanks.
The key marked Delete sends Ctrl-H, Fn+Delete sends DEL.
Thanks.
