### ISSUE TITLE
devdraw: override screen scaling on macOS?

### ISSUE THREAD

**Issue by rsc** [9fans/plan9port#206]
Is there some way in the new Metal devdraw to find out what the applied screen scaling is and then tell macOS, "OK I will apply that myself, please let me supply the actual pixels to put on the screen"?

The default scaling on my 2018 15" MacBook Pro is "looks like 1680x1050" which really means "tell apps they have 3360x2100 and then resample to 2880x1800 before displaying". But then all the work we go through to make good pixels gets thrown away in the resampling. If we knew the intended scaling (in this case 85%) we could scale down fontsrv fonts by 85% and otherwise draw our usual lines, and everything would be crisp.

/cc @jxy

**Comment by jxy** [comment]
We could go the extra miles to get the physical pixel numbers (I'm not sure what would be the best approach) and do all the conversions by ourselves.  I believe it is possible.

I don't think Apple wants you to do that.  I guess they want you to forget about physical pixels, and the application view would scale with how you set the scaling in your system preferences.

**Comment by rsc** [comment]
OK, too bad I guess. Thanks for trying.
