### ISSUE TITLE
devdraw: glitchy flicker in full screen mode on macOS

### ISSUE THREAD

**Issue by 4ad** [9fans/plan9port#207]
Devdraw (or acme, I haven't tested other program) has these weird black screen flickers in full screen mode on macOS.

To reproduce:

1. open acme
2. make it full screen and open a few windows
3. click on some _other_ window (if you were in some window, click another one)
4. switch desktops using 4 finger swipe
5. switch desktop back to full screen acme using 4 finger swipe
6. click on _another_ window than the one clicked at step 3

The screen will glitch. It will either become temporarily black during the click, or it will stay black and you need to click again to redraw it.

This is commit ad2d4950 on 10.14.1 running on an iMac.

**Comment by 4ad** [comment]
Tested on sam, exact same problem.

**Comment by jxy** [comment]
I can confirm that occasionally there is a delay of half a second, before the screen actually displays new contents, whenever display switched to the fullscreen devdraw application.  Though I'm not seeing black screen or graphical glitch.

I have the 2017 13-in MacBook pro with an intel integrated GPU.  What machine do you have.

Here are pure speculations.  It may be related to the composition the mac window system does.  When the application is in windowed mode, the window system does the composition.  When the application is in fullscreen mode, the display bypasses the window system composition.  Things may not be smooth during that transition.

**Comment by 4ad** [comment]
iMac (Retina 5K, 27-inch, Late 2015)
AMD Radeon R9 M395X 4096 MB

**Comment by 4ad** [comment]
Found another way to reproduce (or perhaps it's a different problem): run `for i in `seq 1000`; do echo $i; sleep 1; done` in win, then 4-finger swipe out of acme, then swipe back in. The screen will be black for about half a second.

**Comment by jxy** [comment]
You can turn on the NSLog statement at the beginning of the file and see the event sequence.

Does it help if you change `MTLStoreActionDontCare` to `MTLStoreActionStore`?
