### ISSUE TITLE
fontsrv: option to disable backtick/single-quote remapping

### ISSUE THREAD

**Issue by mattwidmann** [9fans/plan9port#210]
It'd be great if there was a way to prevent the backtick/single-quote remapping here: https://github.com/9fans/plan9port/blob/df2d9ec9d169626cdc2a23829bb2831738215722/src/cmd/fontsrv/osx.c#L39-L44

I find it hard to tell the difference between the two replacement glyphs in fonts like SF Mono, Consolas, and Pragmata Pro. I've attached images of these three fonts displaying `` `foo` 'bar' ``:

- SF Mono: <img width="104" alt="screen shot 2018-11-16 at 11 03 25 pm" src="https://user-images.githubusercontent.com/175115/48658276-fb76ed00-e9f3-11e8-8224-89138b2386f2.png">

- Consolas: <img width="97" alt="screen shot 2018-11-16 at 11 05 12 pm" src="https://user-images.githubusercontent.com/175115/48658282-13e70780-e9f4-11e8-8da7-09b19a02f85c.png">

- Pragmata Pro: <img width="83" alt="screen shot 2018-11-16 at 10 58 51 pm" src="https://user-images.githubusercontent.com/175115/48658284-1c3f4280-e9f4-11e8-930b-4cdce82cc7e7.png">

**Comment by jxy** [comment]
Looks like @rsc is the one to blame.

**Comment by mattwidmann** [comment]
Seems like it. I guess we could add some more exceptions to the whitelist for the typefaces I mentioned, instead of adding an option (or new syntax to the font's path).

**Comment by rsc** [comment]
The differences in Consolas and Pragmata look perfectly clear, Consolas especially. I agree the SF Mono one is hard to tell. If you want to add SF Mono feel free to send a PR, but I'll close this for now.

**Comment by hovsater** [comment]
I've been using acme on Windows for a long time now and recently got a Mac. I just ran into this as well where single quotes and backticks are hard to tell a part.

**DejaVu Sans**

<img width="143" alt="Screenshot 2024-12-04 at 09 21 29" src="https://github.com/user-attachments/assets/52269660-44ef-4876-bc52-b2efb632fe7d">

**Berkeley Mono**

<img width="162" alt="Screenshot 2024-12-04 at 09 22 53" src="https://github.com/user-attachments/assets/00550b01-ea37-409e-903b-cf151f0caffd">

Why do we have these translations in the first place (asking out of curiosity)?

**Comment by hovsater** [comment]
Here's how the Berkley Mono font looks in my terminal:

<img width="156" alt="Screenshot 2024-12-04 at 09 25 11" src="https://github.com/user-attachments/assets/dac0f187-19ff-47f4-acb6-74af8b772995">
