### ISSUE TITLE
devdraw: sometimes the screen reverts to older state

### ISSUE THREAD

**Issue by 4ad** [9fans/plan9port#214]
This is tricky to reproduce.

Sometimes I edit a file in acme, then as I look at it, the screen reverts to the old version of the file (before I did the most recent changes). It's purely a visual thing, the buffer is fine, when I click on the screen, it updates with the current (correct) version of the file.

**Comment by ilanpillemer** [comment]
I noticed this also happens when I got a notification slide in.

**Comment by mattwidmann** [comment]
This happens for me in fullscreen mode, but not in windowed mode. @4ad / @ilanpillemer , are you seeing this only in fullscreen, too?

**Comment by jxy** [comment]
Can you all check out #215?  And let me know if you all experience the same mouse jittery as @4ad does.

**Comment by 4ad** [comment]
I only run in fullscreen mode, so I didn't have the chance to see it otherwise. But by my very limited testing, It's specific to full screen mode, yes.

As to the jittery mouse, it's a very subtle effect, nothing major.

**Comment by mattwidmann** [comment]
Weird: when a notification slides in (on current master), I see the cursor change from the Plan 9 cursor to the macOS one. Seems related, maybe.

**Comment by ilanpillemer** [comment]
Yes, that's correct. In full screen mode, and especially whenever there is
a notification pop up. I've just disabled notifications as they are
annoying anyway and that stops most of it.

**Comment by jxy** [comment]
Can you all check out #215 and provide some suggestions?

**Comment by rsc** [comment]
@4ad, still seeing this after #215?

**Comment by 4ad** [comment]
No, seems to be fixed.
