### ISSUE TITLE
acme: crash when using Edit X/foo/ ,|bar

### ISSUE THREAD

**Issue by jacobvosmaer** [9fans/plan9port#219]
To reproduce:

```
B /tmp/a
B /tmp/b
```

Then in any tag, `Edit X/tmp/ ,|fmt`. I expect this to pipe each file through `fmt` but instead Acme just crashes. The crash doesn't happen if the `X` query matches just one window.

**Comment by jacobvosmaer** [comment]
This might be a duplicate of #9

**Comment by jxy** [comment]
I think plan 9 have the same problem.  Apparently `winunlock` is called without a prior `winlock` at `ecmd.c:/^runpipe/+/winunlock` with the X command.

**Comment by jxy** [comment]
Please test #222

**Comment by jacobvosmaer** [comment]
Cross-posting from #222: it works!
