### ISSUE TITLE
Sam shows error message when closed

### ISSUE THREAD

**Issue by refi64** [9fans/plan9port#22]
On my Ubuntu 14.04 x64 system, I get this in my terminal when I close Sam:

```
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 154 requests (154 known processed) with 0 events remaining.
```

Probably not important but slightly disturbing.

**Comment by bhuntsman** [comment]
I can confirm that this issue is no longer present in current versions of plan9port.
Please close.
