### ISSUE TITLE
devdraw: does not always resize properly

### ISSUE THREAD

**Issue by uluyol** [9fans/plan9port#225]
On my mac, recent changes cause window resizing to be broken in certain situations. Specifically, if I use [Spectacle](https://www.spectacleapp.com/) to resize windows, the contents stretch weirdly. Manually resizing the window fixing this.

Screenshot:
<img width="374" alt="screen shot 2018-12-16 at 5 58 38 pm" src="https://user-images.githubusercontent.com/4128872/50060030-700c8b00-015c-11e9-9f77-ec64b05297ca.png">

**Comment by jxy** [comment]
See #212

**Comment by rsc** [comment]
This should be fixed now thanks to #215.
