### ISSUE TITLE
Inconsistent sam cursor (Yosemite)

### ISSUE THREAD

**Issue by 0branch** [9fans/plan9port#23]
Steps to reproduce under Yosemite (Cocoa retina build):
- Select _new_, _zerox_, _resize_, _close_ or _write_ from the button 3 menu
- Move the pointer around the sam window without clicking

The cursor alternates between the default system pointer (black arrow) and the appropriate sam cursor.

**Comment by 0branch** [comment]
Additional notes:

- I can't reproduce this issue on a non-retina Mavericks machine
- Encountered with the current HEAD, 3aca221

**Comment by mariusae** [comment]
Could you try this?

https://codereview.appspot.com/download/issue79100043_1_10001.diff

(And recompile devdraw.)

**Comment by 0branch** [comment]
Thanks; that seems to fix the problem.

**Comment by rsc** [comment]
All this retina code has been rewritten. Hoping the bug is fixed. I haven't seen this while using sam recently.
