### ISSUE TITLE
Acme macos cursor not focussed after task switch, sometimes

### ISSUE THREAD

**Issue by jacobvosmaer** [9fans/plan9port#232]
I use acme on macos 10.14.1, the new metal backend. Sometimes when I task switch from another app to Acme, the cursor is somehow not focussed. I type on the keyboard but not text appears. Only when I move the mouse does Acme focus on the right window.

I'm not sure how to reproduce this (yet) but it happens quite regularly.

**Comment by jacobvosmaer** [comment]
I think I may have found a way to reproduce.

There are areas in an Acme window where keypresses get ignored. The border between two "typable" areas for instance. I can reproduce if I do this:

- move mouse in Acme to area where keypresses get ignored
- switch to other app
- within other app, move mouse to point where acme _should_ respond to the keyboard
- switch back to acme
- press keys

Result: nothing happens until I move the mouse. I wonder if we're missing some sort of mouse event after switching back.

**Comment by jxy** [comment]
Yes, I understand that the mouse location is not updated (the new mouse location is not communicated to acme) after switching back to acme.  I will take a look at it later.
