### ISSUE TITLE
Troff -ms bug

### ISSUE THREAD

**Issue by aksr** [9fans/plan9port#233]
This is a very old bug (since the same bug is present in `DWB`).

Executing `.KS` after `.1C` exhibits a bug.
Instead on the next page, the text between `.KS` and `.KE` is shown at the bottom of the page
(where footnote would be).  To reproduce the bug:

[http://sprunge.us/xyCUX7](http://sprunge.us/xyCUX7) (The link is *only occasionally* down.)

The bug can be fixed by changing two lines in `tmac.s`:

  1. `if \\n(NX<1 .bp\}` to `if \\n(NX<=1 .bp\}`
  2. `if \\n(NX<1 'bp\}` to `if \\n(NX<=1 'bp\}`

The bug is also present in *vanilla* plan9 and 9front.

**Edit: The bug is fixed in 9front.**

**Comment by rsc** [comment]
Thanks for the diagnosis
