### ISSUE TITLE
rio: Imakefile doesn't list key.c

### ISSUE THREAD

**Issue by espectalll** [9fans/plan9port#235]
For some reason, `rio`'s `Imakefile` doesn't list `key.c` on its `SRCS` and `OBJS` variables:

https://github.com/9fans/plan9port/blob/2607cc565ee3d5facb8949e9acfed35c8ae300c9/src/cmd/rio/Imakefile#L5-L6

This stops the program from compiling at all (standalone), showing up the following log on my computer when doing `xmkmf && make`:

```
gcc -o rio -O2 -fno-strength-reduce -fno-strict-aliasing      -L/usr/lib64   main.o event.o manage.o menu.o client.o grab.o cursor.o error.o color.o -lXext -lX11      
/usr/bin/ld: main.o: in function `main':
main.c:(.text.startup+0x636): undefined reference to `keysetup'
/usr/bin/ld: event.o: in function `mainloop':
event.c:(.text+0x1296): undefined reference to `keyrelease'
/usr/bin/ld: event.c:(.text+0x12a6): undefined reference to `keypress'
collect2: error: ld returned 1 exit status
make: *** [Makefile:1047: rio] Error 1
```

**Comment by rsc** [comment]
Fixed by removing Imakefile. Everything in the tree builds with mk. That's an ancient dreg.

**Comment by espectalll** [comment]
How can I use `mk` for building it then? Keep in mind I'm on Musl so my system is unable to build the entirety of Plan9Port, but it does manage to run `mk` itself.

**Comment by rsc** [comment]
mk install

**Comment by espectalll** [comment]
...but that doesn't work here, if I add `bin/` to `$PATH`, `cd src/cmd/rio` and do `mk install` it returns

```
warning: skipping missing include file /src/mkhdr: No such file or directory
cat: /src/mkmany: No such file or directory
bad include program status
```

**Comment by gdiazlo** [comment]
Use the 9 script to call mk:

    `# /usr/local/plan9/bin/9 mk install`

**Comment by espectalll** [comment]
Thank you! Building with `PLAN9=../../.. 9 mk install` did the trick!
