### ISSUE TITLE
Transpilation to Golang

### ISSUE THREAD

**Issue by Konstantin8105** [9fans/plan9port#237]
Hello!
If you want transpile from C to Golang, then you can use my project [c4go](https://github.com/Konstantin8105/c4go).
Just for example, I take for example folder `plan9port/src/cmd/troff`.
Run `c4go transpile -clang-flag="-I../../../include/" n*.c dw*.c t*.c`.
As result we have Go file.

Some notes about transpilation:
* not every C code can be transpiled to Go. For example, function `getch` from  `plan9port/src/cmd/troff/n1.c:409` have `switch` with `goto` between `case`.
* pointer arithmetic look is not good in Go. For example this function:
```go
// twdone - transpiled function from  $GOPATH/src/templorary/plan9port/src/cmd/troff/n10.c:267
func twdone() {
	if noarch.NotInt(TROFF) != 0 && t.twrest != nil {
		obufp = obuf
		func() int {
			if func() []byte {
				obufp = (*(*[1000000000]byte)(unsafe.Pointer(uintptr(unsafe.Pointer(&obufp[0])) + (uintptr)(noarch.Sprintf(obufp, []byte("%s\x00"), t.twrest))*unsafe.Sizeof(obufp[0]))))[:]
				return obufp
			}() > (*(*[1000000000]byte)(unsafe.Pointer(uintptr(unsafe.Pointer(&obuf[0])) + (uintptr)(8192)*unsafe.Sizeof(obuf[0]))))[:] {
				return flusho()
			}
			return 1
		}()
		flusho()
		if pipeflg != 0 {
			pclose(ptid)
		}
		restore_tty()
	}
}
```
So, if you need help, then please clarify.
Fell free close that issue.

----
Konstantin

**Comment by rsc** [comment]
Thanks for the heads up. For now we'll keep things in C but I am happy to hear about c4go. Best, Russ.
