### ISSUE TITLE
structural expressions

### ISSUE THREAD

**Issue by lego12239** [9fans/plan9port#241]
Hi.

Read the structural expressions paper with examples of possibilities for awk/sed/grep, but can't find structural expressions in plan9 awk/sed/grep.

Are structural expressions implemented only in sam and acme?

**Comment by lego12239** [comment]
@robpike , @rsc

**Comment by robpike** [comment]
No.

**Comment by lego12239** [comment]
ok. Where can i find awk/sed/grep versions with structural expressions support? May be plan9 has another programs with structural expressions?

**Comment by robpike** [comment]
I don't know of any such tools. Sorry. Long story. There's only sam.

**Comment by lego12239** [comment]
ok. Thanks for the reply!

Rob, may be you have some additions to your paper about structural expressions?
May be some new ideas on the same topic?

**Comment by nsajko** [comment]
@lego12239, you might be interested in vis [0], a vim-like text editor that uses structural regular expressions; and in ssam, the "stream sam" (comes with plan9port).

[0] https://github.com/martanne/vis

**Comment by lego12239** [comment]
@nsajko, thanks, but i can use sam & acme as editors with structural expressions support. I want a sed/grep/awk replacement.

> and in ssam, the "stream sam" (comes with plan9port).

This is great! Thanks!

**Comment by lego12239** [comment]
If i understand correctly, ssam can be used as sed & grep replacement.
