### ISSUE TITLE
acme: close button not working on chromeos crostini

### ISSUE THREAD

**Issue by lmumar** [9fans/plan9port#246]
**Hardware**: pixelbook
**OS**: Google Chrome OS Version 72.0.3626.122 (stable build)
**Issue**: 
Acme close button not working on chrome OS crostini. Clicking on the button does not do anything. The only way to close the window is to kill the acme process. Other applications like libreoffice, vscode are working fine.

**Comment by rsc** [comment]
I have no idea what could be causing this. There must be an x11 message that Acme does not respond correctly to, but obviously it seems to work in other Unix window systems.

**Comment by lmumar** [comment]
Hi @rsc thanks for the reply, I'll close this case since I could not help you investigate the issue anymore because I sold my pixelbook a few months ago.
