### ISSUE TITLE
Can have spaces in file or directory name

### ISSUE THREAD

**Issue by blakemcbride** [9fans/plan9port#26]
There is no way to select a directory that has a space in its name, e.g. "MY DIR".  Same for files with spaces in them.  This is the single biggest reason I don't use acme all of the time.

**Comment by gleydsonsoares** [comment]
well, just use $PLAN9/bin/B

eg.:
B 'MY DIR' or B 'FILE NAME'

* Requires plumber(4) running.

**Comment by rbns** [comment]
while this enables opening the files as soon as the window with that file is selected, everything after the space is removed. thus, the file can't be `Put` etc.

maybe we can patch acme so that it understands the behaviour os `ls` from plan9port which wraps paths with spaces in `'`

i can try to look into this, but i don't really know my way round in the acme code. i guess it can't be _too_ hard for someone who understands whats happening

**Comment by blakemcbride** [comment]
I like acme a lot.  Pike made a lot of really good choices that make it a
remarkable editor.  I would use it if I could, but I do not.  I don't
because of a handful of minor things that are major impediments to its
use.  I call them minor things because I believe that they are really easy
to correct.  I don't do it myself because I literally work every moment I
am not spending with what little time I spend with my family.  It is not
possible for me to correct.

I have a very small list of, what I consider, major issues (that are minor
issues to correct).  The number one issue is not supporting spaces between
directory and file names.  Every time I try to make major use of acme I get
hit by this.

IMO, it is also sad that Pike's ideas have become to some a religion.
While Pike has contributed greatly to the field, he's not infallible.  A
few tweaks / corrections to his masterpiece could make all the difference
to the general use and applicability of his ideas.

Just an opinion.

Blake McBride

**Comment by blakemcbride** [comment]
Still can't edit files with spaces in their name or their path.  Also, can't select fonts with spaces e.g. "Courier New".

**Comment by jxy** [comment]
It may not be difficult to use the library functions in quote(3) to perform quote/unquote.  The result may be trivially backward compatible.  @blakemcbride, since you comment on this issue every year, perhaps you can try your hand at it?

**Comment by blakemcbride** [comment]
I check it every so often to see if it now works (or if p9p has disappeared altogether).

**Comment by dertuxmalwieder** [comment]
Adding myself to CC for the time being. I might try to work on this after my stack of other TODOs has been processed. (Which might be in 2020 or so.) Anyone else?

**Comment by henesy** [comment]
Might be time for a deadpixi/sam style rewrite of acme to cover all of these bases that p9p's version doesn't hit.

**Comment by dertuxmalwieder** [comment]
I generally agree, but deadpixi/sam sacrifices a lot (including the deliberate use of no keyboard shortcuts).

**Comment by jxy** [comment]
Don't drop devdraw.

**Comment by deadpixi** [comment]
> I generally agree, but deadpixi/sam sacrifices a lot (including the deliberate use of no keyboard shortcuts).

Deadpixi sam does have keyboard shortcuts. :)

**Comment by dertuxmalwieder** [comment]
Exactly!
