### ISSUE TITLE
cmd/devdraw: color space issues in full screen with macos "Night Shift"

### ISSUE THREAD

**Issue by jacobvosmaer** [9fans/plan9port#260]
macos 10.14.3, plan9port 9179fdaa

I use the "Night Shift" feature available in recent macos versions, which (drastically) changes the color temperature of the display after sunset to go easier on the eyes. It gives everything a warm yellowish tint.

This mostly works as expected with devdraw (acme) except when I use full screen mode. In that case I intermittently but quite often see a jarring effect where the white outline of the mouse cursor is at normal daytime color temperature. It's probably the entire cursor that is wrong but it's most visible on the white outline which becomes bright / blueish in comparison to the rest of the display.

I have not been able to make a screenshot because pulling up the screenshot app seems to reset some display state, and I'm not sure if the screenshots reflect the night shift color temperature to begin with. (I _think_ the screenshots turn out neutral.)

Edit: I think this is not just about the cursor, it's about the color space of the whole window (screen), it's just most visible around the cursor.

**Comment by jacobvosmaer** [comment]
I need to do more work to try and reproduce this. It's not enough to manually turn on night shift.

**Comment by jacobvosmaer** [comment]
It looks like you also need to enable the "automatically adjust brightness" feature, and trigger brightness adjustments (e.g. by blocking light from reaching the sensor used for that).

**Comment by jacobvosmaer** [comment]
OK so not related to auto brightness after all.

- enable night shift (make sure color temperature is on the warm side)
- start acme (as normal window)
- make sure there is a acme window you can type text in
- switch acme to full screen
- type more text

Result: cursor color space gets messed up.

I tried disabling the custom cursor by commenting out `- (void)resetCursorRects`. With that function removed, I get the normal cursor again, but the color problem still happens.

**Comment by jacobvosmaer** [comment]
I also see a jump in the window color after switching to full screen. Maybe the cursor is a red herring? It might be that something is wrong with the colors overall, and it's just most noticeable on the cursor.

**Comment by jacobvosmaer** [comment]
What do you think about this change @jxy?

One way to reproduce this bug is to turn on night shift ("manually enable until sunrise"), switch acme to full screen and then typing and moving the mouse.

**Comment by jxy** [comment]
@jacobvosmaer do you experience the same thing when #215 is applied?

**Comment by jacobvosmaer** [comment]
@jxy it looks like #215 also fixes this issue!

**Comment by jxy** [comment]
I just played with the colorspace a bit.  It looks like setting `layer.colorspace = nil;` solves the issue, too, even though Apple's document says "The default value is nil, indicating that the rendered content is not color-matched."

**Comment by rsc** [comment]
Closing since #215 fixed this.
