### ISSUE TITLE
x11.c:43: error: ‘FC_POSTSCRIPT_NAME’ undeclared

### ISSUE THREAD

**Issue by clintolsen** [9fans/plan9port#269]
I'm trying to build on a pretty old version of CentOS (6.8), and I get:

```x11.c:43: error: ‘FC_POSTSCRIPT_NAME’ undeclared
mk: 9c -I/usr/include/freetype2 x11.c  : exit status=exit(1)                                                    
mk: for i in ...  : exit status=exit(1)
mk: for i in ...  : exit status=exit(1)```

**Comment by fhs** [comment]
`FC_POSTSCRIPT_NAME` is defined in `/usr/include/fontconfig/fontconfig.h`. You need to install `fontconfig-devel`.

**Comment by jxy** [comment]
You need fontconfig 2.11 or up.  The one in CentOS 6.8 is probably too old.

**Comment by clintolsen** [comment]
Is it pretty straightforward to point to an alternate location of `fontconfig`?

**Comment by jxy** [comment]
Add `CFLAGS` and `LDFLAGS` to `$PLAN9/LOCAL.config` for a global effect.  Or edit `$PLAN9/src/cmd/fontsrv/freetyperules.sh` directly.
