### ISSUE TITLE
acme win not working in OpenBSD 6.5-current

### ISSUE THREAD

**Issue by Superpat** [9fans/plan9port#275]
Hi,

There seems to be a problem with win under the latest OpenBSD snapshot. I'm currently debugging this on the ports mailing list, but I'm opening an issue here for completeness.

https://marc.info/?l=openbsd-ports&m=156317908615645&w=2

The main issue seems to be that running win will display a prompt in a new window and accept the first command. It then just hangs until killed.

1. I open win(1) in the command line and the process is sleeping

pmarchan 74306  0.0  0.0  1448  1268 pe  S+      3:25PM    0:00.00 win
pmarchan 29610  0.0  0.0  4896  2396 pe  S+      3:25PM    0:00.02 win

2. I execute a command in the win prompt and one of the processes is idle, the other is waiting on the disk.

pmarchan 74306  0.0  0.0  1448  1268 pe  I+      3:25PM    0:00.00 win
pmarchan 29610  0.0  0.0  4896  2396 pe  D+      3:25PM    0:00.03 win

**Comment by abiscuola** [comment]
Hi

I'm the one that reported the issue on OpenBSD. After upgrading the system to a more recent snapshot, everything started to work fine again.

You can close this issue and sorry for the noise.

**Comment by Superpat** [comment]
It was caused by changes to the openbsd kernel that were later reverted. See here for reference: https://marc.info/?l=openbsd-ports&m=156330905122122&w=2

Since it's now working for me as well, I'll close this issue.
