### ISSUE TITLE
9pfuse: dotdirs() walks open files resulting in Twalk/Rerror transactions

### ISSUE THREAD

**Issue by nicolagi** [9fans/plan9port#276]
The function /usr/local/plan9/src/cmd/9pfuse/main.c:/dotdirs/ was introduced in commit 9ec57f8b9e8a243ca94fbdef0ed571b823a095b7 and is used in /usr/local/plan9/src/cmd/9pfuse/main.c:/fusereaddir/ only. Since you always need to open the dir before reading from it, walking ".." would always fail as per walk(9p). Perhaps that walk to ".." could be simply removed?

Example 9P dialog:

```
Topen tag 0 fid 55 mode 0
Ropen tag 0 qid (dc76e9f0c0006e8f 7cb7f9d4 'd') iounit 0
Twalk tag 0 fid 55 newfid 1 0:'..' 
Rerror tag 0 ename 'bad use of fid' ecode 0
Tread tag 0 fid 55 offset 0 count 8168
Rread tag 0 count 1667
```

**Comment by rsc** [comment]
Fixed.
