### ISSUE TITLE
am porting to minix3?

### ISSUE THREAD

**Issue by kristofer** [9fans/plan9port#29]
can plan9port be ported to a platform with out pthreads?
(minix3)

what I am seeking is to get acme ported to minix3.

any pointers?

**Comment by kristofer** [comment]
this is settling out to the port of libmach and the pthreads stuff. Most everywhere there was a NetBSD preference or means of doing something, I've replicated it for Minix 3.3
if and when it works, I'll produce a PR.

**Comment by kirbyfan64** [comment]
@kristofer I will say [this](https://github.com/9fans/plan9port/blob/master/CONTRIBUTING.md) before everyone else does:

> Plan 9 from User Space uses Gerrit instead of GitHub pull requests. See the codereview(1) man page.
