### ISSUE TITLE
Howto install on android Termux?

### ISSUE THREAD

**Issue by v217** [9fans/plan9port#293]
1. Did anybody manage to install plan9port on [Termux](https://termux.com/)? Or at least the rc shell?

2. Is there an easy way to just compile one cmd (the rc shell)?

Thanks!

**Comment by wgrr** [comment]
On Mon Oct 28, 2019 at 8:34 AM v217 wrote:
> 2. Is there an easy way to just compile one cmd (the rc shell)?
> 
Yes, `cd src/cmd/rc; mk install`.  however if you're interested only
in plan9 shell commands, it should easier for you to install from
[9base](https://tools.suckless.org/9base/).

**Comment by aksr** [comment]
@v217: 
https://github.com/benavento/rc
https://github.com/rakitzis/rc

**Comment by v217** [comment]
@wgrr @aksr  Thanks for the links, there seems to exist a convenient way to get [a chrooted ubuntu environment](https://wiki.termux.com/wiki/Ubuntu) in [Termux](https://wiki.termux.com), so I will try this first. I thought somebody has certainly ported a rc version to android.

**Comment by v217** [comment]
@wgrr Is there an easy way to build just `mk`?

**Comment by mirtchovski** [comment]
see dist/buildmk in p9p. it's the first thing INSTALL does

**Comment by eekee** [comment]
I just tried 9base-6, then plan9port-master, both in main termux, not chrooted. [9base-6 (which is old now) failed with missing header.]  p9p failed with this:
```
* Running on Linux: checking for NPTL...
>>> lib/linux-isnptl.c:9:7: error: expected ';' after expression
        ulong x;
             ^                                                                    ;
lib/linux-isnptl.c:9:2: error: use of undeclared identifier 'ulong'          ulong x;
        ^
lib/linux-isnptl.c:9:8: error: use of undeclared identifier 'x'
        ulong x;
              ^
lib/linux-isnptl.c:11:2: error: use of undeclared identifier 'x'
        x = (ulong)pthread_self();
        ^
lib/linux-isnptl.c:11:7: error: use of undeclared identifier 'ulong'; did you mean 'long'?
        x = (ulong)pthread_self();
             ^~~~~
             long
```
I'm always surprised when ulong is missing.

@v217: Thanks for the chroot link. I like that they suggest VNC for GUI; the RealVNC viewer for Android has good 3-button support. I'll be happy if sam & acme work. :)

**Comment by eekee** [comment]
I changed my mind (see edit), but ran into this missing getcallerpc error, which is more serious than a missing header. I imagine it will block compilation in the Ubuntu root on my tablet, too.  
```
>>> cd /data/data/com.termux/files/home/p9p/src/lib9
9c getcallerpc-aarch64 unknown.c
clang-9: error: no such file or directory: 'getcallerpc-aarch64'
clang-9: error: no such file or directory: 'unknown.c'
clang-9: error: no input files
>>> cd /data/data/com.termux/files/home/p9p/src/lib9
9a getcallerpc-aarch64 unknown.s
usage: 9a file.s
```
And then I got the same error as 9base:
```
>>> cd /data/data/com.termux/files/home/p9p/src/lib9
9c readcons.c
readcons.c:5:10: fatal error: 'sys/termios.h' file not found
#include <sys/termios.h>
         ^~~~~~~~~~~~~~~
1 error generated.
```

**Comment by rsc** [comment]
Not sure there's much to do here. Termux is not a supported build platform. It's clearly very incomplete.

**Comment by eekee** [comment]
Fair enough. I had to stop using my tablet for ergonomic issues, TBH. If I take it up again, I could go for one of the complete chroots.

**Comment by v217** [comment]
rc is now available on Termux!
termux/termux-packages#4469 (comment)
