### ISSUE TITLE
acme does not dump when window is closed

### ISSUE THREAD

**Issue by rogpeppe** [9fans/plan9port#30]
Writing in deep frustration because I accidentally closed
a window and lost hours of work. This has happened before.

Under Ubuntu at any rate, closing an acme window
does not dump current state to $HOME/acme.dump. It should.

**Comment by bopwerks** [comment]
You're spending hours editing an unnamed file, and never saving your work?
That seems to be a personal habit problem, not an editor problem.
Nevertheless, it should be easy enough to modify acme to post a message
when you try to close an unnamed file. Just don't expect anyone else to
solve a problem they don't have...Jesse

**Comment by anths** [comment]
That's a remarkably unhelpful and uninformed response. Acme, on all its platforms, has long created a $home/acme.dump file when it terminates unexpectedly. What rog is reporting is clearly a bug in existing functionality. Note that this has nothing to do with getting "acme to post a message" - Rog isn't closing a file, and the whole point is that acme's no longer around to do any such thing. I suggest you take a look at the existing acme.dump functionality before going farther.

**Comment by anths** [comment]
Rog: does an explicit Dump work, without arguments? I was surprised to see p9p acme always consults $HOME, never $home; could your environment be mismatched?

Beyond that: rowdump calls warning(), but the normal mechanics for getting them printed is gone in the event of a shutdown. Have warnings() print the message it's given. Also, slightly worrying that thread(3) says "The implementation of threadnotify may not be correct.".

**Comment by paulzhol** [comment]
I'm using Dump without arguments to save my workspace and font settings all the time, I didn't even know it was supposed to do that in case of a crash. Is it supposed to catch SIGSEGV and SIGABRT?

**Comment by bopwerks** [comment]
Rog didn't say that acme crashed. He said he accidentally closed an unnamed window that he was working in. How is that a bug?

**Comment by rogpeppe** [comment]
I don't believe I said anything about an "unnamed" window. Anthony has the
scenario right. I fumbled the mouse and closed the main acme window by
mistake. Under plan 9, that causes an automatic dump, the same as if acme
is killed. Under my system it does not.  Dump does work fine for me BTW.

Can others confirm that this is the case for them too please?

Jesse, to address your original point, I actually do believe that the user
should not be responsible for periodically remembering to push the save
button. That's something that computers are excellent at,  and at least
this particular fallible human is not, and I wish acme had this feature.
But that is an orthogonal issue to this one.

**Comment by anths** [comment]
I'm seeing the same thing, on OS X My memory says I've seen acme.dump files auto-generated on p9p in the past, but it's been wrong before. I did a few tests, and it doesn't look to me like shutdown() is ever getting called. I'd want to poke at threadnotify() more (but I have a deadline tomorrow!).
