### ISSUE TITLE
9term and sam on OpenBSD don't have/can't load default fonts

### ISSUE THREAD

**Issue by goleo108** [9fans/plan9port#308]
by default they are just blank windows, but setting font env variable fixes the problem

I can't figure out what causes this, I tried to sed -i 's|/lib/font/bit|/usr/local/plan9/font|' on every file that matched grep '"/lib/font/bit' (just to make sure I won't need to set font env variable in the future for any program)

**Comment by rsc** [comment]
/lib/font/bit turns into unsharp("#9/font"), which should turn into get9root()+"/font".
get9root returns $PLAN9 or else a constant hard-coded in /usr/local/plan9/src/lib9/get9root.c.
That constant should be /usr/local/plan9 or wherever you ran INSTALL.

**Comment by goleo108** [comment]
indeed, that constant is /usr/local/plan9, however, even manually setting PLAN9 env variable doesn't change a thing, but reading the code of functions actually called gives me no idea which one of them fails, there is no output to terminal either...

**Comment by dancrossnyc** [comment]
Sorry dumb question...but did you 'export PLAN9'?

**Comment by goleo108** [comment]
@dancrossnyc yes, `/usr/local/bin/9` script is doing that for me

**Comment by rsc** [comment]
@goleo108, what did you set the font environment variable to?

**Comment by goleo108** [comment]
@rsc `/usr/local/plan9/font/lucsans/unicode.8.font`

**Comment by rsc** [comment]
If $font is not set the programs are supposed to use a font bitmap baked into the binary as data arrays. File system access should not matter. Setting $font would improve matters by reading a file. The /lib/font/bit seems to be a red herring. I bet if you did font=/lib/font/bit/lucsans/unicode.8.font that would work just as well.

One interesting detail thoughtis that to read that font data from an fd, the code creates a Unix domain socket pair (using socketpair(2)) and stuffs the data into one end in its entirety before reading from the other. The font data is 4649 bytes. If the default Unix domain socket buffer is only 4k on OpenBSD that would make the pipe write hang. I would have expected it to be much bigger, but maybe it's only 4k?

It might be interesting to attach gdb to the stuck samterm and try to get a stack trace. Make sure to attach to the higher-numbered pid in the pair of samterm processes.

**Comment by rsc** [comment]
Now that I see you say "they are just blank windows" I'm pretty sure it's the hang I described. Will send a fix.
