### ISSUE TITLE
fix: build fails on freebsd arm64

### ISSUE THREAD

**Issue by rastagraffix** [9fans/plan9port#320]
dist/buildmk fails under FreeBSD on arm64 (Pi 3).  Fix attached (tested on FreeBSD 12.1).

[freebsd.arm64.diff.txt](https://github.com/9fans/plan9port/files/4022523/freebsd.arm64.diff.txt)

**Comment by nsajko** [comment]
@rastagraffix I made a more thorough fix, can you try it: https://github.com/9fans/plan9port/pull/321

**Comment by rastagraffix** [comment]
Neven Sajko writes:

> @rastagraffix I made a more thorough fix, can you try it: https://github.com/
> 9fans/plan9port/pull/321

I can't rebuild at the moment, but the patch looks fine.
