### ISSUE TITLE
The getcallerpc situation

### ISSUE THREAD

**Issue by nsajko** [9fans/plan9port#324]
I would like to discuss the getcallerpc function, its uses, and its
implementations.

The problem with its implementations currently is that they are wrong,
and that it is involved to make them correct.

The main issue is that the approach used for getcallerpc can not be
implemented in portable C. One set of issues is all the things the C
standards forbid, like out of bounds access. But even if we had all the
implementations in assembly, there would still be the issue of
functions being inlined.

Thus I think the only possible way to reliably implement getcallerpc is
by using compiler-specific extensions, or stuff that relies on them,
like Ian Lance Taylor's libbacktrace.

Apart from that, the implementation for, eg., AMD64 is just totally
nonsensical, in fact it is just a copy of the file intended for i386.

With that in mind, the question arises: is getcallerpc even needed? I
mean, it is just used as a debugging tool, and there could be other
ways to debug if the need arises.

One possible solution, without getting rid of the getcallerpc concept,
would be to use `__builtin_FUNCTION` or `__FUNCTION__` if GCC or Clang are
doing the compiling, and give a constant otherwise (eg., 0xeffeabbe).

Are there other possibilities?

**Comment by dancrossnyc** [comment]
Meh. Just put in a stub that returns zero.

**Comment by rsc** [comment]
It doesn't really matter that they are wrong. They are only for debugging, and no one is using them. I replaced them with the compiler builtins or else a function that returns 1.

**Comment by nsajko** [comment]
> It doesn't really matter that they are wrong. They are only for debugging, and no one is using them.

It wasn't just a matter of correctness of getcallerpc, but (formally, at least) of whole program correctness. At least on my platform (AMD64) the implementation caused Undefined Behavior, which could have meant an unpredictable defect in the compiled binary.

**Comment by rsc** [comment]
FWIW, if that code broke the entire binary you have a broken compiler, no matter what the spec says.
