### ISSUE TITLE
getcallerpc issues

### ISSUE THREAD

**Issue by mek** [9fans/plan9port#328]
Clone the repo today: http://sprunge.us/RgfSwp

OpenSUSE 15.1 with the latest updates. 
ar: getcallerpc-x86_64.o: No such file or directory

Tested on Mac also, the same error is given. 
Did have a chance to check out an older version a test, was just putzing around in a meeting. Sorry I can't offer more info now, but if needed I can do so later.

**Comment by nsajko** [comment]
mkmk.sh needs to be updated, as in #326

**Comment by Makhor** [comment]
Has this issue been resolved yet? Should I wait for the next commit?

**Comment by nsajko** [comment]
@makhor, just apply #326, specifically the src/mkmk.sh change (just two lines).

**Comment by nsajko** [comment]
This issue should be fixed now on master.
