### ISSUE TITLE
[acme] Missing pixel(s)

### ISSUE THREAD

**Issue by aksr** [9fans/plan9port#33]
(Linux)
1. Open acme
2. Click on **New** tag
3. Click anywhere on the tag field, for example, after **Look** tag
    (in the body field, press _Enter_ (to pull cursor down) - the (missing) pixels are _easier_ visible)
(I think two pixels are missing)
 ![image1](http://i.imgur.com/YN3W3N2.png)

If _Enter_ is pressed, the pixels reappear:
 ![image2](http://i.imgur.com/OOhl4jO.png)

also, if _Backspace_ is pressed when cursor is here:
 ![image3](http://i.imgur.com/TAJYSam.png)

returns the pixels for the moment:
![image4](http://i.imgur.com/FJSFflx.png)

pressing _anything_ (_Space_ etc.) removes them.

**Comment by markvanatten** [comment]
Thanks for the report. I see the same on OSX 10.10.3.

Mark.

**Comment by chyvonomys** [comment]
button and modbutton images (top left corner rectangles) were created with two extra columns of bright blue pixels, and they were overwriting thin divider producing these two missing pixels
