### ISSUE TITLE
devdraw: full screen on mac no longer hides the menu bar

### ISSUE THREAD

**Issue by jxy** [9fans/plan9port#333]
In full screen mode, the menu bar appears when user moves the cursor to the upper edge of the screen.  Previously it would remain hidden.

**Comment by rsc** [comment]
Thanks for the quick fix as always.

**Comment by rsc** [comment]
I committed the fix. Is it working for you?

**Comment by rsc** [comment]
It is not working for me. But then none of my apps successfully hide the dock in full screen, not Chrome, not Safari, not Firefox, not Messages. I wonder if Catalina is broken?

**Comment by rsc** [comment]
Oh I see you really meant the menu bar. I mean the dock. I will open a separate issue.

**Comment by rsc** [comment]
The dock bug is #336.
