### ISSUE TITLE
INSTALL fails on freebsd

### ISSUE THREAD

**Issue by bakul** [9fans/plan9port#334]
INSTALL fails on both FreeBSD x86 and x86_64 with

    9c does not know how to compile on FreeBSD-386-cc

or

    9c does not know how to compile on FreeBSD-x86_64-cc

Looks like INSTALL adds CC9=clang and then removes it.  Adding
it manually and then doing mk all in src/lib9 makes it work.

Looks like a dispute between INSTALL and 9c on FreeBSD!  Not
sure what the right fix is.

**Comment by rsc** [comment]
> Looks like INSTALL adds CC9=clang and then removes it. 

I see the adds but not the "then removes it". Where is the removes?

**Comment by bakul** [comment]
From `sh -x INSTALL`:
```
+ Submitting changes: https://github.com/9fans/plan9port/pulls
+ echo ' '

+ echo '* Resetting /usr/local/plan9/config'
* Resetting /usr/local/plan9/config
+ rm -f config
+ tee install.log

```
