### ISSUE TITLE
devdraw: full screen on mac hides the dock even on another screen

### ISSUE THREAD

**Issue by rsc** [9fans/plan9port#336]
Full screen mode on the Mac does not hide the dock, which makes the bottom of the app hard to use. Unclear why.

**Comment by rsc** [comment]
NSApplicationPresentationHideDock is suspiciously absent from 
https://developer.apple.com/documentation/appkit/nsapplicationpresentationoptions/nsapplicationpresentationhidedock?language=objc

**Comment by rsc** [comment]
StackOverflow got me to 3d1382b9.
It would be good to figure out whether the window is on the display with the dock and only turn off the dock in that case. Right now I think if you full-screen on a 2nd display that does not have the dock, the dock disappears from the 1st display. But that's probably still an improvement. More people have just 1 display.

**Comment by jxy** [comment]
That 3d1382b does not seem to help.  If you full screen, and then command-tab out and command-tab back, dock starts to appear again.

**Comment by jxy** [comment]
Comparing `mainScreen` and and the first object in `screens` should tell you whether the window is on the first display or not.  https://developer.apple.com/documentation/appkit/nsscreen/1388371-mainscreen?language=objc

If switching focus gives back the dock to you too, maybe setting the presentation options again when in fullscreen in `windowDidBecomeKey` would help.

**Comment by rsc** [comment]
Tried again and now I can't reproduce the original problem on either Mojave or Catalina (was seeing it on Catalina last night). Will just back out the forced hiding I added and close this.
