### ISSUE TITLE
El Capitan support

### ISSUE THREAD

**Issue by themihai** [9fans/plan9port#34]
Acme fails to load in El Capitan
![screenshot 2015-06-21 17 03 33](https://cloud.githubusercontent.com/assets/1800192/8272371/8993c492-1837-11e5-9af3-e926d72d154b.png)

**Comment by themihai** [comment]
It seems a workaround is to minimise and then maximise the window.

**Comment by kare** [comment]
I'm running El Capitan 10.11 Beta (15A278b) and Acme is running fine.

**Comment by JohnDDuncanIII** [comment]
I am having the same problem on build 15A278b in acme. Going fullscreen/windowed and minimize/maximize seem to fix the problem. I have also been having some issues in XQuartz, so I'm assuming this is just a graphics driver bug (I run a pretty beat up hand-me-down 2009 macbook pro).
