### ISSUE TITLE
acme: doesn't resize on linux

### ISSUE THREAD

**Issue by mjibson** [9fans/plan9port#340]
acme no longer resizes after 892b3c4687eacf6b090bb9a5196ce882e113c423. I'm on Linux using i3.

**Comment by jxy** [comment]
Actually, after 1f79949, nothing resizes on mac.

**Comment by palmamartin** [comment]
I can confirm that resizing does not work on macOS Mojave 10.14.6 anymore.

**Comment by gdiazlo** [comment]
What I see is that windows are resizable, but contents are not updated after a resize, is that what you're seeing right?

In X11, under KDE the windows can be resized but on window creation, the content is a black screen and after resize a white screen. On windows move, mouse or other events contents remain either black or white, depending if a resize happened or not.

In X11 (undex Xnest) using plan9port rio and twm , contents are only redraw on a resize event, on mouse, keyboard and  windows move, contents are not updated.

**Comment by jroimartin** [comment]
Related: https://github.com/9fans/plan9port/issues/339

@gdiazlo same thing [here](https://github.com/9fans/plan9port/issues/339#issuecomment-574470576).
