### ISSUE TITLE
acme broken: empty screen, no controls, no windows

### ISSUE THREAD

**Issue by lego12239** [9fans/plan9port#343]
Hi.

I updated to last plan9port commit and got broken acme. It started, but show just absolutely empty white screen. On every approx. 5th run it works normal.

Last worked commit is 933b98054f40bb224acda134d7bb77a023bcc57f.
Commit which is built, but not worked is 50923426bf684402160dd7748f14560afd447b73.
Commits between these aren't built.

**Comment by lego12239** [comment]
WM - wmii 3.9.2
xorg 7.4
glibc 2.29
gcc  9.2.0

**Comment by dancrossnyc** [comment]
Pull and try again. Russ just fixed a deadlock in fmt that might be related.

**Comment by lego12239** [comment]
Tried it(a9b462061c05f8cd4e1f85b05522770293c8a468). The same.

**Comment by hngt** [comment]
Still persists after pulling.
WM - bspwm 0.9.9
gcc 8.3.0
glibc 2.29

**Comment by 0intro** [comment]
I've been experiencing the same issue. The problem was caused by this change: 1f799495e4aa89be5f32e3fcda8da342f3057f3c

**Comment by 0intro** [comment]
If you start acme in floating mode, it works, but it hangs when you switch full screen.

**Comment by 0intro** [comment]
Before this change, the issue (that appeared a few days ago in the devdraw changes) was that you had to move the mouse after switching full screen so the window refreshes. But the fix doesn't seem to work properly.

**Comment by 0intro** [comment]
I think the issue is that `c->mouse.resized = 1` is not set anymore when calling `gfx_replacescreenimage`.

**Comment by 0intro** [comment]
I did this change as a workaround:

```
--- a/src/cmd/devdraw/srv.c
+++ b/src/cmd/devdraw/srv.c
@@ -397,6 +397,9 @@ matchmouse(Client *c)
 void
 gfx_mouseresized(Client *c)
 {
+	qlock(&c->eventlk);
+	c->mouse.resized = 1;
+	qunlock(&c->eventlk);
 	gfx_mousetrack(c, -1, -1, -1, -1);
 }
 
```

@rsc What is the correct way to implement this?

**Comment by rsc** [comment]
Thanks, I just reached the same conclusion. I put the fix in the mousetrack -1 case.

**Comment by jxy** [comment]
Maybe put it inside that if block in gfx_mousetrack?

**Comment by 0intro** [comment]
Thanks @rsc. It seems to work.

**Comment by lego12239** [comment]
I've got some new problem. acme segfaulted when i piping text to external command. May be this is issue only for 933b98054f40bb224acda134d7bb77a023bcc57f commit.

Steps:
1. place text in the window:
some
text
2. place in the tag >cat
3. select text and click on the >cat with the middle mouse button

On the 5-15 clicks acme segfaulted with message:
acme: reading wsys msg: Connection reset by peer
Segmentation fault

**Comment by 0intro** [comment]
@lego12239 Please open a new issue, so it makes tracking issues easier.

**Comment by lego12239** [comment]
> Thanks, I just reached the same conclusion. I put the fix in the mousetrack -1 case.

Not worked :-).

**Comment by lego12239** [comment]
> I've got some new problem. acme segfaulted when i piping text to external command. May be this is issue only for [933b980](https://github.com/9fans/plan9port/commit/933b98054f40bb224acda134d7bb77a023bcc57f) commit.
> 
> Steps:
> 
>     1. place text in the window:
>        some
>        text
> 
>     2. place in the tag >cat
> 
>     3. select text and click on the >cat with the middle mouse button
> 
> 
> On the 5-15 clicks acme segfaulted with message:
> acme: reading wsys msg: Connection reset by peer
> Segmentation fault

This issue is not exist in the last commit.
