### ISSUE TITLE
acme: empty screen when starting in full screen on x11

### ISSUE THREAD

**Issue by lego12239** [9fans/plan9port#347]
Hi.

I updated to last plan9port commit and got broken acme. It started, but show just absolutely empty white screen. On every approx. 5th run it works normal.

Last worked commit is 933b980.
Commit which is built, but not worked is 5092342.
Commits between these aren't built.

**Comment by lego12239** [comment]
The last fix didn't help.

**Comment by lego12239** [comment]
In floating mode acme works. But wmii start acme in fullscreen mode immediately.

**Comment by rsc** [comment]
Does clicking on the white screen make anything appear?

**Comment by lego12239** [comment]
> Does clicking on the white screen make anything appear?

No. Resizing also makes nothing.

**Comment by lego12239** [comment]
Wow!
- start acme in floating mode
- success
- switch to fullscreen mode
- success
- switch to floating mode
- success
- resize
- got empty window

**Comment by 0intro** [comment]
OK. I can reproduce the last issue you mentioned. The windows becomes empty when starting acme in floating mode, then resizing the window.

**Comment by 0intro** [comment]
Same thing in tiled mode. Starting acme, then resizing the window makes it blank.

**Comment by lego12239** [comment]
> Same thing in tiled mode. Starting acme, then resizing the window makes it blank.

In my case, in tiling mode acme started already blank :-). No need for resizing :-D.

**Comment by 0intro** [comment]
@lego12239 Did you rebuild devdraw and acme after the last commit?

**Comment by rsc** [comment]
Reproduced and fixed.

**Comment by lego12239** [comment]
Oh yes. I do ./INSTALL :-).

**Comment by 0intro** [comment]
@rsc Thanks. It works after your fix.

**Comment by lego12239** [comment]
Works.
Thanks!
