### ISSUE TITLE
devdraw: B1 stuck in B2 mode when entering (, ), {, or } followed by a newline

### ISSUE THREAD

**Issue by danieljamespost** [9fans/plan9port#352]
I am running a fresh install of plan9port on Debian and when entering (, ), {, or } followed by a newline in Sam or Acme, the mouse button 1 gets stuck in execute mode as can be seen in this [example](https://drive.google.com/open?id=16KofdgKX-lZnQk5xSb-Rg_0GRcmK07VO). In order to get the mouse to function normally again, I have to press Escape or Ctrl+Button 1. If I use [Edwood](https://github.com/rjkroege/edwood) with [duitdraw](https://github.com/ktye/duitdraw) instead of p9p devdraw, the problem is not present. If I run Edwod with devdraw, the problem returns which leads me to think this is a devdraw related issue.

**Comment by rsc** [comment]
This looks like a really fun bug, but I can't reproduce it on Debian or on macOS.
What system are you using?
Is there anything special about it?

**Comment by rsc** [comment]
I would think somehow we missed the Shift key up event after you typed a shifted character, or maybe when typing shift-newline. But shift turns B1 into B3, not B2.

**Comment by jxy** [comment]
Can you perform the same key sequence in xev, and paste the recorded key events here?

**Comment by danieljamespost** [comment]
I'm running a pretty minimal net install of Debian 10 Buster on a Thinkpad X1 Carbon gen 6 with dwm and st so I can't imagine that there is much that could be interfering with these events. I use the colemak keyboard layout configured with xkbmap. However, the issue persists regardless of my keyboard layout. 

[Here](https://drive.google.com/open?id=1HUwUF9ACB-iGhaowyKiXHsA1Shg-V_YH) is a dump from xev of me repeating what I did in the example video.

Thanks for taking a look at this.

**Comment by jxy** [comment]
You have to first give xev the focus and then typing out the key sequence.

**Comment by danieljamespost** [comment]
My mistake. [Here](https://drive.google.com/open?id=1-1l3xSWwnPR_YkpH7Bde30PkgwRFZf-I) is the updated dump from xev.

**Comment by rsc** [comment]
I don't know if it's your system or xev or what, but that's a very strange trace. Notice how the keystrokes are often released before they are pressed. For example here's the very first letter, i:

```

KeyRelease event, serial 21, synthetic NO, window 0x4a00001,
    root 0x16a, subw 0x0, time 40912407, (377,109), root:(2298,129),
    state 0x0, keycode 46 (keysym 0x69, i), same_screen YES,
    XLookupString gives 1 bytes: (69) "i"
    XFilterEvent returns: False

KeyPress event, serial 21, synthetic NO, window 0x4a00001,
    root 0x16a, subw 0x0, time 40912407, (377,109), root:(2298,129),
    state 0x0, keycode 46 (keysym 0x69, i), same_screen YES,
    XLookupString gives 1 bytes: (69) "i"
    XmbLookupString gives 1 bytes: (69) "i"
    XFilterEvent returns: False
```

Those have the same time stamp but xev logged the release before the press. If devdraw is getting key-up events before the key-downs, that won't matter for most letters because it only cares about one or the other, but it absolutely matters for whether Shift is held down across mouse clicks.

**Comment by jxy** [comment]
What command do you use to change to colemak?  Can you try a new X11 session without using xkbmap?

**Comment by danieljamespost** [comment]
Here's a sample from typing vi in a new X session without running any xkbmap commands:
```
KeyRelease event, serial 22, synthetic NO, window 0x1600005,
    root 0x16b, subw 0x0, time 43343186, (1201,100), root:(1202,120),
    state 0x0, keycode 55 (keysym 0x76, v), same_screen YES,
    XLookupString gives 1 bytes: (76) "v"
    XFilterEvent returns: False

KeyPress event, serial 22, synthetic NO, window 0x1600005,
    root 0x16b, subw 0x0, time 43343186, (1201,100), root:(1202,120),
    state 0x0, keycode 55 (keysym 0x76, v), same_screen YES,
    XLookupString gives 1 bytes: (76) "v"
    XmbLookupString gives 1 bytes: (76) "v"
    XFilterEvent returns: False

KeyRelease event, serial 22, synthetic NO, window 0x1600005,
    root 0x16b, subw 0x0, time 43343298, (1201,100), root:(1202,120),
    state 0x0, keycode 55 (keysym 0x76, v), same_screen YES,
    XLookupString gives 1 bytes: (76) "v"
    XFilterEvent returns: False

KeyRelease event, serial 22, synthetic NO, window 0x1600005,
    root 0x16b, subw 0x0, time 43344242, (1201,100), root:(1202,120),
    state 0x0, keycode 31 (keysym 0x69, i), same_screen YES,
    XLookupString gives 1 bytes: (69) "i"
    XFilterEvent returns: False

KeyPress event, serial 22, synthetic NO, window 0x1600005,
    root 0x16b, subw 0x0, time 43344242, (1201,100), root:(1202,120),
    state 0x0, keycode 31 (keysym 0x69, i), same_screen YES,
    XLookupString gives 1 bytes: (69) "i"
    XmbLookupString gives 1 bytes: (69) "i"
    XFilterEvent returns: False

KeyRelease event, serial 22, synthetic NO, window 0x1600005,
    root 0x16b, subw 0x0, time 43344346, (1201,100), root:(1202,120),
    state 0x0, keycode 31 (keysym 0x69, i), same_screen YES,
    XLookupString gives 1 bytes: (69) "i"
    XFilterEvent returns: False
```

It has the same issue. For reference, here's my .xinitrc after removing xkbmap commands:
```
export VISUAL=editinacme
export EDITOR="$VISUAL"

# Fire up apps
xscreensaver -no-splash &

# daemons
nm-applet &
blueman-applet &
udiskie &
xfce4-power-manager &

while true; do
    slstatus
done &

exec dwm
```

**Comment by rsc** [comment]
Interesting. From that trace it's more obvious that each keystroke results in three events: release, press, release, where the first two have one time stamp and the third is a bit later. That wouldn't be a problem, so maybe that's not worth investigating further. I had missed the other weird thing in the trace: the release, press, release for shift sends "release Shift\_L", "press Shift\_L", "release Caps\_Lock" (!).

```
KeyRelease event, serial 21, synthetic NO, window 0x4a00001,
    root 0x16a, subw 0x0, time 40914247, (377,109), root:(2298,129),
    state 0x0, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 21, synthetic NO, window 0x4a00001,
    root 0x16a, subw 0x0, time 40914247, (377,109), root:(2298,129),
    state 0x0, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 21, synthetic NO, window 0x4a00001,
    root 0x16a, subw 0x0, time 40914351, (377,109), root:(2298,129),
    state 0x1, keycode 35 (keysym 0x7d, braceright), same_screen YES,
    XLookupString gives 1 bytes: (7d) "}"
    XFilterEvent returns: False

KeyPress event, serial 21, synthetic NO, window 0x4a00001,
    root 0x16a, subw 0x0, time 40914351, (377,109), root:(2298,129),
    state 0x1, keycode 35 (keysym 0x7d, braceright), same_screen YES,
    XLookupString gives 1 bytes: (7d) "}"
    XmbLookupString gives 1 bytes: (7d) "}"
    XFilterEvent returns: False

KeyRelease event, serial 21, synthetic NO, window 0x4a00001,
    root 0x16a, subw 0x0, time 40914455, (377,109), root:(2298,129),
    state 0x1, keycode 35 (keysym 0x7d, braceright), same_screen YES,
    XLookupString gives 1 bytes: (7d) "}"
    XFilterEvent returns: False

KeyRelease event, serial 21, synthetic NO, window 0x4a00001,
    root 0x16a, subw 0x0, time 40914559, (377,109), root:(2298,129),
    state 0x1, keycode 50 (keysym 0xffe5, Caps_Lock), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

MotionNotify event, serial 21, synthetic NO, window 0x4a00001,
    root 0x16a, subw 0x0, time 40914887, (376,109), root:(2297,129),
    state 0x0, is_hint 0, same_screen YES

MotionNotify event, serial 21, synthetic NO, window 0x4a00001,
    root 0x16a, subw 0x0, time 40914895, (376,109), root:(2297,129),
    state 0x0, is_hint 0, same_screen YES

```

The keycode is the same for all three events but in the final release the keysym changes from Shift\_L to Caps\_Lock.

We could work around that I guess. Is it (the Caps\_Lock change) still happening without xkbmap etc?

**Comment by jxy** [comment]
That's similar to what I had when I created #253 (I still haven't got around to update the X11 devdraw yet).  The keysym of the key release event is different from the keysym of the key press event, so I had to save the keycode to properly detect the key release event.

**Comment by rsc** [comment]
@jxy if you want to refresh that patch and merge it in, that's fine with me. Thanks.

**Comment by jxy** [comment]
I'll get around to it next week.

**Comment by rsc** [comment]
Thanks very much!

**Comment by danieljamespost** [comment]
I found part of the issue. Somewhere deep in my $home/lib/profile I pulled in a script that added the following xkbmap options on top of the settings in .xinitrc:
```
setxkbmap -option ctrl:nocaps
setxkbmap -option 'caps:ctrl_modifier'
```
These options must have conflicted with this setting in my .xinitrc in some strange ways that weren't immediately obvious:
```
setxkbmap us -variant colemak -option ctrl:nocaps -option shift:both_capslock
```
After removing the script from lib/profile, events are firing as expected and the mouse related issue has gone away. Thank you very much for your help and I apologize I didn't realize this earlier.

**Comment by jxy** [comment]
I can't find any documents about X modifier keysym changes like so, but I do have my shifts working funny with `Option "XkbOptions" "grp:shifts_toggle,caps:hyper"` in `xorg.conf`.  I just updated #253, and you can check if it fixes things for different configurations with `setxkbmap`.
