### ISSUE TITLE
Delete key on OS X version of Acme Editor doesn't in fact delete

### ISSUE THREAD

**Issue by robertAtDejero** [9fans/plan9port#37]
Steps to reproduce:
- From terminal, type  `acme -al`
- mouse over to a window or title bar.
- hit the delete key

Expected:
- forward delete behaviour as is standard across all other applications

Result:
- prints a strange unicode icon

Context:
Some research into the matter turned up this PDF (http://www.quanstro.net/newbie-guide.pdf) that indicated that the Delete key is mapped to stopping processes, much in the way that  Ctrl-C does in traditional UNIX.

I have not seen any benefit to printing this unicode icon when editing text files. I would like to suggest that a compiler flag be added to give users the opportunity to remap the Delete key to forward delete.

Thank you! I really appreciate all the work being done on this project and use the editor every day.

**Comment by andrewchambers** [comment]
You could do this by patching acme yourself and maintaining your own github fork.

**Comment by robertAtDejero** [comment]
I appreciate your faith in my programming prowess.  I would rather defer to those who know a great deal more about programming in C than I.

**Comment by mehlon** [comment]
This would break `win(1)` behavior, which kills the current process when the delete key is pressed.

**Comment by rsc** [comment]
For betterr or worse we are going for verisimilitude with Plan 9.
If people got used to typing DEL to delete forward in text windows
they'd be very sad when they type DEL in a win window and it kills
the running program instead.
