### ISSUE TITLE
fontsrv X11: incorrect baseline

### ISSUE THREAD

**Issue by dzklaim** [9fans/plan9port#372]
Apparently, the baseline of fonts is incorrect when using X11. This leads to clipped letters like in #18 

Changing src/cmd/fontsrv/x11.c:81 to match f->height scaling seems to solve the problem (also "because" is misspelled).

`f->originy = face->descender * 1.35; // bbox.yMin (or descender)  is negative, because the baseline is y-coord 0`

**Comment by markvanatten** [comment]
Could you turn this into a pull request?

**Comment by dzklaim** [comment]
done!

**Comment by markvanatten** [comment]
Thanks!

**Comment by rsc** [comment]
Applied.
