### ISSUE TITLE
acme: bottom of symbols is cut with dejavu font 

### ISSUE THREAD

**Issue by lego12239** [9fans/plan9port#375]
Hi.

I changed a size of font from 14 to 20 and can't see underscores :-).

**Comment by lego12239** [comment]
dejavu:
![screenshot](https://user-images.githubusercontent.com/1998711/77182924-98610300-6ade-11ea-85d2-e2ac6ec96fec.png)

another:
![screenshot](https://user-images.githubusercontent.com/1998711/77183091-db22db00-6ade-11ea-949c-c6878bdeaf60.png)

**Comment by lego12239** [comment]
The last image is source-code-pro font, but here we can see that symbols is cut too.

**Comment by dzklaim** [comment]
you may wanna try the pull request mentioned in #373.

**Comment by lego12239** [comment]
> you may wanna try #373.

Thanks for info, but this fix don't help me :-(.

**Comment by dzklaim** [comment]
You can try to toy around with the scaling factor like in #373 and #111.

**Comment by lego12239** [comment]
It's works :-). I see underscores even without #373. The fact was that i used ttf2subf instead of fontsrv :-). Why nobody told me about fontsrv earlier :-)?..

**Comment by lego12239** [comment]
But DejaVu Serif only works good with  #373.
