### ISSUE TITLE
acme: insertion in a tag doesn't expand it

### ISSUE THREAD

**Issue by lego12239** [9fans/plan9port#383]
Step to reproduce:
- paste with mouse a text(which longer than remain space) in a tag
** tag isn't expanded
- scroll a tag or move a cursor with a keyboard to expand a tag

Is that normal or a bug :-)?

**Comment by rsc** [comment]
It's normal - tags originally never expanded, and we made expansion opt-in instead of changing the default behavior. Those two cases you mentioned might merit an auto-expansion, though. Do you know how much code it is? If the diff looks small we can think about it. Thanks.

**Comment by lego12239** [comment]
If it's normal, it's ok. Just reporting :-).
