### ISSUE TITLE
No longer builds on RHEL/CentOS 6 or 7.

### ISSUE THREAD

**Issue by khm** [9fans/plan9port#390]
https://github.com/9fans/plan9port/commit/9505cd15a64933bf58ec50548339cf98b1854646 breaks the build on RHEL 6.  

RHEL 6 retirement date is 2020-11-30.  End of support is 2024-06-30.  

I'm not sure it's worth fixing, but I figured it was worth reporting.

**Comment by yarikk** [comment]
Neither on CentOS 7 (perhaps, RHEL 7, too): [gcc 4.8 lacks stdatomic.h](https://stackoverflow.com/questions/20326604/stdatomic-h-in-gcc-4-8)

**Comment by khm** [comment]
Confirmed; same behavior on CentOS 7 and RHEL 7.  

RHEL 7 retirement date is 2024-06-30.  End of support is not set but likely to occur in 2028.

**Comment by rsc** [comment]
Fixed by c3c9c7b6ae7c6a8bf9c6d040d3af89e020fd92de.
Not sure how I wrote 'fixes #55' when I meant 'fixes #390.'

**Comment by khm** [comment]
The fix is incorrect; stdatomic.h came with GCC 4.9. #391 builds.
