### ISSUE TITLE
[9term] [sam] [acme] run failure: 'settag/send tag 1: Broken pipe'

### ISSUE THREAD

**Issue by rprimus** [9fans/plan9port#396]
Mon May 18 08:20:42 BST 2020

<details>
<summary>OS info:</summary>
macOS:
<pre>
: ; sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G5027

XQuartz 2.7.11 (xorg-server 1.18.4)
</pre>
</details>

I've just rebuilt after recent commits.

Both '9term' and 'sam' are failing to run with the above error (repeated):
```
: ;  sam
settag/send tag 1: Broken pipe
settag/send tag 1: Broken pipe
settag/send tag 1: Broken pipe
settag/send tag 1: Broken pipe
```

`acme` also fails to run and has a segmentation fault:
```
: ; acme
settag/send tag 1: Broken pipe
settag/send tag 1: Broken pipe
settag/send tag 1: Broken pipe
settag/send tag 1: Broken pipe
settag/send tag 1: Broken pipe
settag/send tag 1: Broken pipe
settag/send tag 1: Broken pipe
settag/send tag 1: Broken pipe
settag/send tag 1: Broken pipe
[1]    2281 segmentation fault  acme
```

These occur after X has been started.

**Comment by gdiazlo** [comment]
Seems like the process is dying and the writing fails. It might be related to the recent change of `devdraw` and `ClientImplementation`. There are calls to `c->impl ` in devdraw.c that the X11 screen does not seem to implement yet. I think we need to create a `ClientImplmentation` for X11, pointing to the correct functions already implemented in `x11-screen.c`

**Comment by gdiazlo** [comment]
I've added the correspondent `mac-screen.m` lines to `x11-screen.c` at it seems to work here. Just a quick snarf&paste.

**Comment by rsc** [comment]
Fixed with @gdiazlo's changes.
