### ISSUE TITLE
fontsrv: unicode beyond 0xffff

### ISSUE THREAD

**Issue by gdiazlo** [9fans/plan9port#401]
I was trying a recent change about supporting runes bigger than 0xffff, but so far, I can't get it to work. I don't know if it is related to the fonts I tried, or may be fontsrv needs to be fixed to support them on x11.

I can see there are differences on x11 vs mac, like src/cmd/fontsrv/x11.c:88
```
		if(charcode > 0xffff)
			break;
```

I tried to naively remove that, but no luck :( 

Any hints in how to add support for it on x11/linux? the alt :, shows pjw face instead of the face with tears of joy.
thanks

**Comment by rsc** [comment]
I never said I got it to display, just that typing it worked. I ran the command "unicode <ALT : ,>" and it printed 1f602.

It may be that fontsrv needs updating - that had not occurred to me. I thought the problem was just that my fonts didn't have the character.

**Comment by gdiazlo** [comment]
Oh! I misunderstood then, sorry. The fonts in linux are kind of weird with a lot of font management systems old a new laying around, I never got the grasp of it. :(

**Comment by jxy** [comment]
We also can't use alt-X sequence for input beyond 0xffff, because it recognizes 4 hex digits only.

**Comment by rsc** [comment]
Should be fixed now. Alt-X-X-12345 and Alt-X-X-X-103456 for longer hex sequences.
