### ISSUE TITLE
acme x11: growing window draws wrong border size

### ISSUE THREAD

**Issue by wgrr** [9fans/plan9port#404]
I'm running current master p9p, often i noticed this weird slightly bigger borders drawn after window 'grow' button click, i finally have a reproducible test case. (at least, on my machine: ubuntu 18.04, gcc 7.5.0, plan9port master)

1. `$ acme` then **Dump**, **Exit**
2. `$ acme -f $font` $font can be any font other than what was used to generate the acme.dump file, (tested with Go, Hack and lucsans/euro, dump files i've been using attached below)
3. **Load** and **New** 3 windows, make enough room for all of 3, in the middle window make its tag have at least 2 lines (and ensure it's drawn)
4. click the last window 'grow' button.

here's what i could gather so far, i hope this might help someone willing debug further than what i could myself:

  `$ acme -l` works properly
  some font sizes draws a larger border than others (see screenshots)
  dragging the window instead always work
  only happens when multi line tags are shown in upper window
  i couldnt reproduce while **Load** is matching with -f argument
  i did tested with master and d2df5d6, both reproduces
  applying #373 didnt helped
  the border rect is drawn here: https://github.com/9fans/plan9port/blob/4650064aa757c217fa72f8819a2cf67c689bcdef/src/cmd/acme/cols.c#L445

test dump files:
[gofont.acme.dump](https://github.com/9fans/plan9port/files/4675150/acme.dump.txt)
[lucsans.acme.dump](https://github.com/9fans/plan9port/files/4675395/acme.dump.txt)

screenshots

GoMono/10a/font in dump file, `$ acme -f GoMono/14a/font`:

![2020-05-25-014226_864x576](https://user-images.githubusercontent.com/16732610/82778863-013f6100-9e29-11ea-9687-3bc484072f46.png)

GoMono/10a/font in dump file,  `$ acme -f lucasans/euro.8.font`:

![2020-05-25-013826_864x576](https://user-images.githubusercontent.com/16732610/82778689-7494a300-9e28-11ea-8023-e892a79bac8c.png)

lucsans/euro.8.font in dump file, `$ acme -f GoMono/12a/font`:

![2020-05-25-025031_864x576](https://user-images.githubusercontent.com/16732610/82782409-a579d580-9e32-11ea-96d5-b9f4fb061208.png)

**Comment by iburago** [comment]
I can reproduce the issue on macOS (10.15.5), as well.

**Comment by chyvonomys** [comment]
Similar repro:
1. open acme.
2. create 2 windows in one column
3. change font in first window to something that has different height than default
4. make first window tag multiline
5. make second window grow

Turns out border rectangle calculation was wrong and its height was > Border pixels high. My simple change fixes that.
