### ISSUE TITLE
Unix Path aliases not honored

### ISSUE THREAD

**Issue by ealvarezn** [9fans/plan9port#447]
On plan9port in Linux, at least, acme cannot follow paths that use tilde as an alias for the user's home directory (eg, `~/path/to/foo`) or the `$HOME` environment variable (eg, `$HOME/path/to/foo`). This happens regardless of what value `$acmeshell` has been set to. It'd be nice if acme could honor these aliases.

**Comment by iburago** [comment]
If by “following paths” in acme(1) you mean the ability to open them
with button 3, it is entirely a matter of plumber(4) configuration
(which you can also benefit from in sam(1), 9term(1), etc.).

For instance, here is the relevant fragment of my `plumbing` file that
makes plumb(1) work with paths starting with `~/` and `$HOME/`:

```
# To fill out the below 'home' variable in acme(1), put the
# cursor between the single quotes and drag-select the Edit
# command with button 2:
home = ''  # Edit <printf %s $HOME

include fileaddr  # $PLAN9/plumb/fileaddr

ccfilename = 'A-Za-z¡-�0-9_\-.,'
ccpathnospace = $ccfilename'/'
ccpath = $ccpathnospace' '

# File paths starting with '~' and '$HOME'
type is text
data matches '(~|\$HOME)/(['$ccpath']+)('$addr')?'
arg isfile	$home/$2
plumb start plumb -a 'addr='$4 $file

# Directory paths starting with '~' and '$HOME'
type is text
data matches '(~|\$HOME)/(['$ccpath']*)'
arg isdir	$home/$2/
data set	$dir
plumb to edit
plumb client $editor
```

(I also have a similar configuration for paths starting with `$PLAN9/`.)

Unfortunately, one still has to type the full path to the home directory
to interactively complete partial paths starting with it via <kbd>Ctrl</kbd>+<kbd>F</kbd> in
acme(1), as there is no way to configure that completion mechanism
without directly modifying it in the source code.

**Comment by rsc** [comment]
Acme also doesn't do glob expansion or environment variable substitution or any other shell interpretation.
That's just not its job.
