### ISSUE TITLE
how acme display chinese font

### ISSUE THREAD

**Issue by ivoidi** [9fans/plan9port#458]
I want edit chinese document inside acme, but it cannot display

**Comment by rsc** [comment]
Is the document UTF-8?
What font are you using?

**Comment by ivoidi** [comment]
Yes, the document is in UTF-8 encoding.
It is my font set problem, after switching the font supporting Chinese, it can display normally. 
Thank you very much.

Now i cannot use Chinese input method in acme. 
I use Gnome3 ibus-libpinyin input method, after switching to this, i still input english.
I donnot know how to do it

**Comment by fhs** [comment]
@ivoidi There is some early support for X input methods in #426.

**Comment by ivoidi** [comment]
@fhs 
I‘ve tried it just now. I can input Chinese now. Thanks
There may be cursor tracking problem, i will continue follow.
Thanks for your works
