### ISSUE TITLE
Rio does not start on Linux

### ISSUE THREAD

**Issue by hatesgh** [9fans/plan9port#482]
I've installed plan9port via the Arch repository. If I run `9 rio` or `rio`, it will just print out:
`rio: can't open display: Success`
I tried killing X on where I started it (`/dev/tty1`) and start Rio there, but same thing. I Googled this issue and looked for it in the mailing list, but I didn't get any results. Is there actually no Rio or something? What's going on?

**OS:** Artix Linux

**Comment by fhs** [comment]
rio works fine here on Arch Linux. That error probably means you don't have the DISPLAY environment variable defined.

**Comment by hatesgh** [comment]
```
DISPLAY=':0'
$ 9 rio
rio: can't open display: Success
$ echo $DISPLAY
:0
$
```
Still.

**Comment by hatesgh** [comment]
I've figured it out! It was *so* obvious, I am so stupid.
I just had to edit my `.xinitrc`, like with any new WM being tried out.
