### ISSUE TITLE
Connection refused when running '9p ls' on Debian Linux

### ISSUE THREAD

**Issue by sirnewton01** [9fans/plan9port#495]
I'm trying to use the "9p ls" command to browse the namespace and I keep getting errors like the following both inside and outside of acme:

```
9p ls /
9p: mount: dial unix!/tmp/ns.cmcgee.:0/: connect /tmp/ns.cmcgee.:0/: Connection refused
```

**Comment by gdiazlo** [comment]
The 9p tool needs to connect to a 9p server. In plan9port environment, you can list what services are running a 9p server by listing the contents of the namepsace (see 9 man namespace) diretory, which is usually /tmp/ns.$USER.$DISPLAY/, but you can set one arbitrarily by using the NAMESPACE environment variable.

```
$ ls `namespace`
acme		factotum	font		plumb
$ 9p ls factotum
confirm
conv
ctl
log
needkey
proto
rpc
```

**Comment by sirnewton01** [comment]
Thank you, this is the bit that I needed to understand. So, every 9p server that I launch will create a service in my namespace?

**Comment by gdiazlo** [comment]
That's the intended behaviour. See the plan9port intro manual page with `9 man intro`. It describes how it works and why, and explains the differences between the plan9port behaviour and the plan9 native behaviour. Section 4 in particular covers this topic.
