### ISSUE TITLE
strange fossil thread issue (100% CPU load) on  Linux armv7

### ISSUE THREAD

**Issue by vestein463** [9fans/plan9port#498]
I noticed that sometimes fossil gets into a 100% CPU loop, sometimes even 200% (dual processor, I think).

I am connecting using 9pfs from FreeBSD with authentication. The auth server - if that matters - is a raspberry pi4 running 9front. The 200% load probably resulted when something went wrong on the FreeBSD side, such as umount the file system or killing the 9pserve there.  

I attached gdb to the fossil process. Gdb listed about 26 LWPs but otherwise was always in a libc call.

Otherwise the combo is working as intended,

**Comment by fhs** [comment]
I think this is fixed by https://github.com/9fans/plan9port/pull/453.

**Comment by vestein463** [comment]
Thanks. I thought I had  newest version installed, but this patch was not yet installed here.
