### ISSUE TITLE
cmd/acme: hang while switching fullscren mode in osx

### ISSUE THREAD

**Issue by masiulaniec** [9fans/plan9port#5]
Acme's window will turn all-gray and hang forever if the user presses 2 keys and the touchpad in the following order:
1. Hold the cmd key down.
2. Hold touchpad down.
3. Press the 'f' key.

**Comment by smazga** [comment]
I was able to reproduce this a few weeks ago, but can't now. Is it still an issue?

My current environment:
MacBook Pro (15-inch, Mid 2012) (non-retina)
OS: 10.10.3 (14D72i)
plan9port: 3aca22118d808597bc7451adc559d89460ed5a6e (Wed Feb 18 09:45:14 2015 -0500)
XQuartz 2.7.7 (xorg-server 1.15.2)

**Comment by masiulaniec** [comment]
Still breaks here.

**Comment by echosa** [comment]
I can confirm this is still happening with the current HEAD of master. 

MacBook Pro (Retina, 15-inch, Mid 2014)
OS 10.10.3

**Comment by rsc** [comment]
We've rewritten a few times and I can't reproduce this. Hopefully it is fixed.
