### ISSUE TITLE
how to send selection to win bash, and execute it

### ISSUE THREAD

**Issue by ivoidi** [9fans/plan9port#500]
in one window, i can use below clause send selection to another window

e.g: send selection to window: win (ID is 2)  that run bash
|9p write acme/2/body
but, win bash not execute the selection

how can i do it, thanks for your help

**Comment by bhuntsman** [comment]
This question would be better asked on the mailing list.  As it is not a code issue, please close.

**Comment by ivoidi** [comment]
ok, thanks
