### ISSUE TITLE
lib9p: postmountsrv() has no implementation

### ISSUE THREAD

**Issue by bladedvox** [9fans/plan9port#505]
It is in `PLAN9/src/lib9p/post.c`, but if you link it and recompile the library, then there is an unimplemented reference to the function `rendezvous()`. I got my 9p server up with `threadpostmountsrv()`, but afaik this is undocumented and it was pretty confusing to say the least.

(This is on Void Linux glibc version using the plan9port package from the repos, if that matters)

**Comment by bhuntsman** [comment]
This is not an error.  rendezvous is not implemented in plan9port.  None of the code in plan9port calls postmountsrv, but always uses threadpostmountsrv, as you discovered.  Perhaps postmountsrv and the routines in uses in _post.c should be removed.

**Comment by JohnDDuncanIII** [comment]
I am unable to install plan9port on the latest macOS due to https://github.com/9fans/plan9port/commit/385a6d5877258cee0cac6151e6359c9206006b01

https://github.com/9fans/plan9port/pull/518

```bash
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

```bash
$ git pull
Already up to date.
```

```bash
$ uname -rms
Darwin 20.6.0 arm64
```
```bash
$ ./INSTALL 
...
* Resetting /config
* Running on Darwin...
* Compiler version:
	Apple clang version 12.0.5 (clang-1205.0.22.11)
* Building mk...
* Building everything (be patient)...
>>> mk: don't know how to make '/opt/plan9/lib/lib9p.a(_post.o)' in /opt/plan9/src/lib9p
mk: for i in ...  : exit status=exit(1)
```

**Comment by dancrossnyc** [comment]
I just committed a fix for that; give it a whirl?

**Comment by JohnDDuncanIII** [comment]
👍🏻 Thanks!
