### ISSUE TITLE
man pages from github.io are 404 Not Found

### ISSUE THREAD

**Issue by RalphCorderoy** [9fans/plan9port#506]
Viewing https://9fans.github.io/plan9port/unix/, the links for the man pages, like isalpharune(3) are 404 Not Found: https://9fans.github.io/plan9port/unix/man/isalpharune3.html

**Comment by bhuntsman** [comment]
This is an issue with the 9fans/9fans.github.io repository, not plan9port.
Please remove it here and open it on that repository.

**Comment by RalphCorderoy** [comment]
Thanks for the pointer.  Done: https://github.com/9fans/9fans.github.io/issues/2
