### ISSUE TITLE
Paste text into sam editor from an external application

### ISSUE THREAD

**Issue by revrari** [9fans/plan9port#510]
I am running the editor sam as a standalone application on Linux. So far I have not been able to figure out a way to paste text into the bitmap display from an external Linux application. Is there a way to achieve this?

**Comment by rsc** [comment]
Sam has its own cut-and-paste buffer separate from the OS. To swap sam's and the OS's, you use the middle-button `<rio>` menu item. (rio is the name of the window system it is swapping buffers with on Plan 9.)

**Comment by alaa2amz** [comment]
`$sudo apt install xsel`
then in sam you can perform command
`< xsel -b`
it shall paste clipboard in the point
