### ISSUE TITLE
plot produces no output on El Capitan

### ISSUE THREAD

**Issue by rennis250** [9fans/plan9port#53]
Does anyone here use the plot command? It runs, but produces no output. Minimizing and re-maximizing the window has no effect. Forcing it to full-screen changes the gray background to white and the menu now appears when one right clicks, whereas it didn't appear when the window was initially opened. Not sure about what could be wrong here. For comparison, cmapcube runs just fine.

Also, is it possible to save the final output from plot to a file for later viewing? That would be really helpful.

**Comment by polluks** [comment]
See http://thread.gmane.org/gmane.os.plan9.general/69779/

**Comment by rennis250** [comment]
Apparently, Gmane may be permanently down: https://lars.ingebrigtsen.no/2016/07/28/the-end-of-gmane/

Any idea what kind of information was present at that link?

Best and thanks,
Rob

**Comment by gleydsonsoares** [comment]
On Fri, Aug 19, 2016 at 7:30 AM, Robert J. Ennis
<notifications@github.com> wrote:
>
> Apparently, Gmane may be permanently down: https://lars.ingebrigtsen.no/2016/07/28/the-end-of-gmane/
>
> Any idea what kind of information was present at that link?


Looks like archive.org has a copy of it.
http://web.archive.org/web/20160728163839/https://lars.ingebrigtsen.no/2016/07/28/the-end-of-gmane/

// gsoares

**Comment by polluks** [comment]
How about this? https://groups.google.com/forum/#!topic/comp.os.plan9/7Qcxiy1ZrNc

**Comment by rsc** [comment]
Fixed a while back. There were some 64-bit problems in the code.
