### ISSUE TITLE
wrong window size on start

### ISSUE THREAD

**Issue by camoles** [9fans/plan9port#54]
when some p9p app like 9term, acme or sam is started under some window manager that changes its size, like the tilling window manager dwm, it does not detect that it's size has been changed and thus do not repaint itself. Because of that, the window seems to think it has a different size than it actually has. It becomes more obvious starting sam under dwm, because it's colors are not white. See example attached. When the user does anything that induces a repaint on the window, like a resize or changing to another tag and back, the problem is solved.

To reproduce: start dwm, and start sam.
Tested with plan9port-20160122  under OpenBSD 5.9 and dwm 6.1, but also reported to me by Linux users using dwm and other window managers that change the window size to their will. For example, window maker allows you to set that a certain program should be started maximized. If you do so to some p9p program, the bug reported here will happen.

Never saw this bug happen to any other program under dwm nor under any other window manager.

![2016-03-31-114657_1917x1079_scrot](https://cloud.githubusercontent.com/assets/7726917/14185245/73ef76ca-f74f-11e5-8187-858a20f7e310.png)

**Comment by gituser1357** [comment]
Quick fix, hardcoding windowrect to screenrect, so the app assumes it is full screen, no status bar: 
https://github.com/gituser1357/plan9port/commit/c15ec21b1802f4ed02d89156d731fa8f09644688
YMMV.

**Comment by camoles** [comment]
But what if the app is not the only one on the screen? This fix is worse than the problem.

**Comment by camoles** [comment]
"If you use Xlib to create your own top-level windows (direct children of the root window), you must observe the following rules so that all applications interact reasonably across the different styles of window management:

You must never fight with the window manager for the size or placement of your top-level window.
You must be able to deal with whatever size window you get, even if this means that your application just prints a message like ``Please make me bigger'' in its window."

source: https://tronche.com/gui/x/xlib/window/create.html

**Comment by eekee** [comment]
*blinkblinkblinkblink* uh.. buh.. wha...t is this i don't even...

i mean the "fix", good grief! "ymmv" indeed. on the other hand, maybe gituser1357 can come over and fix my network; i can't pull or push over http right now, and i can't fix it to save my life! :) or maybe i just need chuck norris to 'talk' to my isp; they're blocking http but nothing else.

now then, x11 apps & window managers:
when opening a window, the app requests a size. the window manager may change that size when mapping the window. (i can't remember the exact details, i last tackled this around 2007, but i know this happens before the window is mapped.) i expect what p9p apps[1] do is assume the requested size was accepted. this was never the right thing to do. 

i'll have a look at the code in a bit. i should have looked at it years ago; i'm not camoles but i'm pretty sure i contributed to the report above via irc chat. it's basically been the same for years under so many different window managers.

**Comment by rsc** [comment]
The code does this when creating the window:

        /*
         * Put the window on the screen, check to see what size we actually got.
         */
        XMapWindow(_x.display, w->drawable);
        XSync(_x.display, False);

        if(!XGetWindowAttributes(_x.display, w->drawable, &wattr))
                fprint(2, "XGetWindowAttributes failed\n");
        else if(wattr.width && wattr.height){
                if(wattr.width != Dx(r) || wattr.height != Dy(r)){
                        r.max.x = wattr.width;
                        r.max.y = wattr.height;
                }
        }else
                fprint(2, "XGetWindowAttributes: bad attrs\n");

It also responds to XConfigureEvents that resize the window.

I found that windowrect was not being updated with the new r, and I fixed that, but I don't see how that would cause the behavior described, since windowrect only applies when toggling full screen mode manually.

I'm going to close this. If it gets reported again maybe we can get more information about the X messages involved.
