### ISSUE TITLE
9term: pasted buffer does not show when reading stdin

### ISSUE THREAD

**Issue by camoles** [9fans/plan9port#55]
If you paste something on a 9term while a program is reading STDIN, the value will be pasted but won't be shown on the terminal. The bug does not happen if something was previously typed manually before pasting.

How to reproduce:
- open 9term
- type the cat command and ENTER
- copy any text to the clipboard
- paste to 9term

The text won't show on the terminal. But it is there, and if you press ENTER cat will echo it. Also, if you type anything after you started the program reading STDIN but before pasting, then the pasted text will show normally.

Tested on openbsd 5.9, under both fvwm, rio and dwm window managers. Using ksh shell.

**Comment by eekee** [comment]
not seen on linux 3.2.29, x.org 1.12.3, twm.

**Comment by tiago4orion** [comment]
Reproducible here using 9term, bash and rio. I don't know if the same happens with rc.

Linux 4.3.3 (x86_64)

**Comment by camoles** [comment]
On openbsd, the bug does not happen if using the rc shell

**Comment by eekee** [comment]
ah. :) yes i have seen this before. bash, ksh, and i imagine most other shells put the terminal into raw mode. you'll want to select 'cook' from the mb2 menu to get them to play nice. or, the shells themselves may have some option.

**Comment by camoles** [comment]
Indeed, if I select the "cook" mode the problem goes away. Also, $TERM is set to 'dumb' by default under 9term. If I set it to say, vt100, the problem also goes away. But I am pretty sure having the apps believe they are running under vt100 when we are under 9term is not the best idea.

Any suggestion about some suitable $TERM value?

**Comment by camoles** [comment]
hmm, interestingly there is the "9term" option under the possible $TERM values. But still, it does not make the bug here related go away. Although it seem to fix some things. For example, if I open "top" under 9term with $TERM set to "dumb", the terminal just closes. Whereas if I set $TERM to "9term", it presents an correct output.

**Comment by camoles** [comment]
It looks like this behaviour is documented on 9term man page:

          9term changes behavior according to the terminal settings of
          the running programs.  Most programs run with echo enabled.
          In this mode, 9term displays and allows editing of the
          input.  Some programs, typically those reading passwords,
          run with echo disabled.  In this mode, 9term passes keys-
          trokes through directly, without echoing them or buffering
          until a newline character.  These heuristics work well in
          many cases, but there are a few common ones where they fall
          short.  First, programs using the GNU readline library typi-
          cally disable terminal echo and perform echoing themselves.
          The most common example is the shell bash(1). Disabling the
          use of readline with ``set +o emacs'' [sic] usually restores
          the desired behavior.  Second, remote terminal programs such
          as ssh(1) typically run with echo disabled, relying on the
          remote system to echo characters as desired.  Plan 9's ssh
          has a -C flag to disable this, leaving the terminal in
          ``cooked'' mode.  For similar situations on Unix, 9term's
          button 2 menu has an entry to toggle the forced use of
          cooked mode, despite the terminal settings.  In such cases,
          it is useful to run ``stty -echo'' on the remote system to
          avoid seeing your input twice.


set +o emacs #fixed the problem here

**Comment by camoles** [comment]
Since I didn't find a way to automate "set +o emacs" (putting it on my .profile wasn't enough), I ended up setting SHELL=rc on my .profile so that 9term uses the rc shell instead of ksh.

**Comment by eekee** [comment]
i always use it with rc. i set $SHELL in my `9` script, and i always start 9term with `9`. 

i'm generally happy with chording cut/paste rather than using history, and i prefer rc's syntax for lots of things. i make functions for oft-repeated commands. you may however wish to `ln -s .profile .bashrc`, or find some other hack to always source .profile or to initialize non-login shells.
