### ISSUE TITLE
acme: Issue with accented characters.

### ISSUE THREAD

**Issue by ealvarezn** [9fans/plan9port#585]
I've configured my keyboard using the setxkbmap utility, as follows:

`setxkbmap -layout "us (intl)" -option ctrl:nocaps -option compose:ralt`

However, when I attempt to type in an accented character, either using the dead keys in the keyboard, or via the compose character, I instead get each character separately (eg, if I type ' and a to get á, I instead get 'a). Interestingly enough, however, caps lock is working as a control key.

**Comment by wgrr** [comment]
That's not how you insert those characters in plan9, for `á` type the sequence `Alt`, `'` and `a`. It's not limited to letters though, `Alt`, `:` and `)`  inserts ☺ (U+263A), more of those sequences can be found in `$PLAN9/lib/keyboard`. You can insert any Unicode hex values too, `Alt`, `X` followed by four hex digits. See [keyboard(6)](https://9p.io/magic/man2html/6/keyboard)
