### ISSUE TITLE
Can't mount plan9 filesystem on Linux

### ISSUE THREAD

**Issue by arturfabriciohahaedgy** [9fans/plan9port#586]
I think this may be a dumb question, but I have been trying for a couple of days now and I just can't figure it out. I heard that to be able to edit the plumbing rules and to make scripts for acme I had to mount plan9 to my filesystem.

Following [mount(1)](https://9fans.github.io/plan9port/man/man1/mount.html) and [9pfuse(4)](https://9fans.github.io/plan9port/man/man4/9pfuse.html) on Arch Linux (installed using the [plan9port package](https://archlinux.org/packages/community/x86_64/plan9port/)) if I try to do a ```9 mount `namespace`/acme /mnt/acme``` I receive the following: 
```fusermount: user has no write access to mountpoint /mnt/acme``` 
If I add sudo:
```
sudo 9 mount `namespace`/acme /mnt/acme
9pfuse: fsmount: permission denied
```
I also tried using 9pfuse as mentioned before, putting the address of a random port a value, but the only thing I get is 9pfs running on TCP but no connection to the actual filesystem. Again, sorry if this is a dumb question but I don't really know how to proceed.

**Comment by wgrr** [comment]
It's not required that you mount plumb, you can use 9p: `9p write plumb/rules < your_rules`. The whole mount of fuse is that you don't need root to mount, so why are using a directory you can't write? try chaging `/mnt/acme` to anything you can write, for example, mkdir -p $HOME/mnt && 9 mount \`namespace\`/acme $HOME/mnt

**Comment by arturfabriciohahaedgy** [comment]
Hi, thanks for the reply!

Using your suggestion I was able to mount plumb, but not acme. So then I tried doing a `acme -m $HOME/mnt/acme` and it worked! So I guess the issue could be closed now...
