### ISSUE TITLE
9c: some binaries produce segmentation faults when compiled for ARMv7 with GCC on Linux

### ISSUE THREAD

**Issue by aoeu** [9fans/plan9port#59]
After running the `INSTALL` command on a machine with ARMv7-A architecture, GCC, and Linux, some of resulting binaries compiled via `9c` (such as `acme` and `9pserve`) terminated with segmentation faults.  However, other binaries can run without issue. (e.g. It was possible to spot-edit in the '-marm' GCC optimization flag in `9c` with `sam -d` and re-run the `INSTALL` command to get everything compiled and running without segmentation faults.)

I believe the segmentation faults have something to do with GCC defaulting to the "Thumb" instruction set on relevant ARM chips, but I could use some guidance on how to best debug and diagnose further.

An incidental fix is to add the `-marm` GCC optimization flag to `cflags` in the case of ARMv7-A chips in order to utilize the ARM instruction set instead of the Thumb instruction set. Would that be too specific of a change to `9c` and would it require a more detailed explanation as to why it works (and why the `-mthumb` GCC default does not)? 

The machine I can consistently reproduce all of this on features a [Rockchip RK3288](https://en.wikipedia.org/wiki/Rockchip_RK3288) (ARM Cortex A-17).  I have a few other machines with ARMv7-A or ARMv8-A I could try reproducing on too, if that helps.

**Comment by dancrossnyc** [comment]
So much has changed in the last three and a little-more than a half years, I'm going to close this. If it comes up again, please re-open.

**Comment by nsajko** [comment]
I _think_ this is still an issue (but can not test it right now).

Context: ARM has multiple instruction sets (sometimes, even usually, supported by the same CPU): Thumb and Thumb2, "old" ARM (A32), and the 64-bit ARM A64. Certain special jump instructions are used for switching between them at run time. The "old" ARM (A32) instruction set is nowadays basically deprecated, for example the Cortex-M cores do not even support it.

The trouble is, as far as I understand, the libthread arm assembly is written so it would assemble to the "old" ARM (A32) instruction set, and GCC will compile C to Thumb and Thumb2 code.

The fix could maybe be making it known that the assembly-defined routines are A32, or to compile everything to A32, like aoeu did. But probably the better fix would be to assemble to the newer Thumb and Thumb2 instruction sets in the first place. This would require some changes to the simple assembly in libthread. Probably `.syntax unified` should be used. Will investigate when I have more time.

**Comment by nsajko** [comment]
@aoeu If you are still interested please try master and my https://github.com/nsajko/plan9port/tree/assemblyTypeFunc regarding this issue. I expect master to still be broken for ARM, and my very simple fix to solve the issue.
