### ISSUE TITLE
9term launches child process with SIGCHLD blocked [linux]

### ISSUE THREAD

**Issue by sqweek** [9fans/plan9port#6]
src/cmd/9term/rcstart.c

`rcstart()` forks a child process to exec the shell. Before the exec there are two calls like `sys("stty ...")`.

`sys()` ends up calling `notedisable("sys: child")`, which blocks SIGCHLD via `sigprocmask()`. However, there is no corresponding call to `noteenable()`, so at the time of `exec()` SIGCHLD is still blocked. The signal mask is not reset on exec, which causes problems for programs that expect to receive SIGCHLD but don't explicitly unblock the signal.

For a concrete example, running `9term gdb 9p` and then executing `start` at the gdb prompt just hangs. If I insert a wrapper program that unblocks SIGCHLD and execs its args, `9term unblkchld gdb 9p`, then executing `start` at the gdb prompt causes execution to stop when 9p enters `main()`, as expected.

**Comment by hardenedapple** [comment]
Just wondering -- is there a reason this change hasn't been put back into the repo?

It would be handy for me too.
