### ISSUE TITLE
m1 darwin issues

### ISSUE THREAD

**Issue by 9arcia** [9fans/plan9port#603]
I am not sure if it was a recent macOS update that broke plan9port, but now I get this message: 

```
bin/acme: exec devdraw: No such file or directory
acme: can't open display: muxrpc: unexpected eof
```
If I recall correctly it was working well a few months ago. I'm not sure when was the last time I tried plan9port.

**Comment by rastagraffix** [comment]
Demian Garcia writes:

> bin/acme: exec devdraw: No such file or directory
> acme: can't open display: muxrpc: unexpected eof

A bit more info about your setup would help.  How recent is
your plan9port build?  What version of MacOS?  Hardware model?

I just did a pull and rebuilt and it's working fine for me.

Darwin hqmac49.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64
2021 MacBook Pro w/M1 Pro CPU

--lyndon

**Comment by gdemian** [comment]
System Version: macOS 13.2.1 (22D68)
      Kernel Version: Darwin 22.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Chip: Apple M1 Pro
      Total Number of Cores: 8 (6 performance and 2 efficiency)
      Memory: 16 GB
      System Firmware Version: 8419.80.7
      OS Loader Version: 8419.80.7

**Comment by gdemian** [comment]
> ```
>   System Version: macOS 13.2.1 (22D68)
>   Kernel Version: Darwin 22.3.0
>   Boot Volume: Macintosh HD
>   Boot Mode: Normal
>   Chip: Apple M1 Pro
>   Total Number of Cores: 8 (6 performance and 2 efficiency)
>   Memory: 16 GB
>   System Firmware Version: 8419.80.7
>   OS Loader Version: 8419.80.7
> ```

The non-GUI elements build fine, only when I try to launch gui-plan9 applications is when it begins to fail on me. I'm not sure where to start looking, either something is corrupted on my system of I'm missing a piece of software.

**Comment by xelxebar** [comment]
@9arcia Why did you close this issue? If you discovered the underlying issue, please share.

**Comment by 9arcia** [comment]
@xelxebar apologies I forgot to follow up. it was simple user error. I simply had to put it in my path correctly. I am using the fish shell, and was unfamiliar on how it was done correctly.

**Comment by xelxebar** [comment]
@9arcia Thanks.
Hrm. Arguably, `sam` and `acme` shouldn't be relying on `PATH` and instead look directly under `9PATH/bin`. Maybe this is a path fixup issue during the install process?
