### ISSUE TITLE
acme: up/down keys on linux behave like page up/down?

### ISSUE THREAD

**Issue by btmura** [9fans/plan9port#64]
Hello,

On Linux, the up/down keys behave like page up and page down. I'm using plan9port-20140306.tgz from the Google Code site.

On Windows, the up/down keys move line by line as expected (in acme-sac).

Any ideas how I can fix this on Linux? Do I need to change the source code for KDown to something? How to figure out the right value?

I saw some postings talk about the unusual behavior of up/down keys on Acme, but I'm not sure what they mean. Are they not supposed to move the cursor line by line?

Thank you!

**Comment by mccoyst** [comment]
The normal acme behavior is for up/down to scroll the window. If acme-sac behaves differently, that's their customization. If I recall correctly, acme-sac is written in a different language, so it may not (or may) be helpful to compare their code. I vaguely remember somebody posting a patch to comp.os.plan9 (a.k.a. 9fans) to change this, but I don't know where it is in the archives.

**Comment by btmura** [comment]
Thanks, mccoyst. How do you move up and down line by line in normal Acme?

**Comment by mccoyst** [comment]
Point and click 😬

**Comment by mariusae** [comment]
@btmura, @mccoyst another trick is to use ctrl-e, right-arrow, or ctrl-a, left arrow.

**Comment by btmura** [comment]
Got it. Thanks!

**Comment by pmarin** [comment]
@btmura I think the canonical way of scrolling line by line in acme is to position the mouse pointer in the scroll window exactly one line of distant from the top and and use the right button. Russ explains this on a youtube video.
