### ISSUE TITLE
no catclock

### ISSUE THREAD

**Issue by chee** [9fans/plan9port#65]
hi

are there any plans to include games/catclock in plan9port?

i still fire up a virtual machine with plan9 every day just for catclock

**Comment by chee** [comment]
i will pay

**Comment by pmarin** [comment]
I actually ported catclock to p9p  many years ago. I don't have the sources but I think changed only like 3 lines of code. 
9vx/9front (in derpy mode), plan9port and wine/9pm:   

![](https://c2.staticflickr.com/8/7345/8731510430_88d6998904_c.jpg)

**Comment by rsc** [comment]
No, because catclock was never included in the open source release.
