### ISSUE TITLE
Bug: Acme: Acme mangles $PATH on Linux

### ISSUE THREAD

**Issue by spektrokalter** [9fans/plan9port#671]
# Expected behavior

Acme shouldn't touch $PATH.

# Unexpected behavior

It adds the path of plan9port binaries to the beginning of the PATH.

Thus, Acme runs Plan 9 programs by default, which is contrary to plan9port's stated recommendation to put the path of the binaries to the end of PATH:

> . . . it is not recommended to put $PLAN9/bin before the usual system bin directories in your search path. Instead, put it at the end of your path and use the 9(1) script when you want to invoke the Plan 9 version of a traditional Unix command.

https://9fans.github.io/plan9port/man/man1/intro.html

# Steps to reproduce the problem

Run Acme on Linux.

Create an empty window with the following content:

<env | grep '^PATH='

# plan9port version

20240617-1, from the official Arch Linux repos.

# OS version

Arch Linux

**Comment by lufia** [comment]
I tried this steps on my Arch Linux but I couldn't reproduce the problem.

Arch's plan9port package has [custom acme script](https://gitlab.archlinux.org/archlinux/packaging/packages/plan9port/-/blob/main/acme.sh?ref_type=heads).

What happen to replay these steps with **/usr/lib/plan9/bin/acme**?

**Comment by spektrokalter** [comment]
Thank you @lufia for the suggestion. Indeed, it works as expected if I run Acme directly, that is /usr/lib/plan9/bin/acme.

Arch's custom script causes the problem by running `9 acme`. It's really this "9" that breaks $PATH, which is likely expected.

I think the issue can be closed by now, because it's, in fact, a distro-specific problem.
