### ISSUE TITLE
Alternative license?

### ISSUE THREAD

**Issue by Happy-Ferret** [9fans/plan9port#73]
Since Plan9 has been available under the GPL for quite some time, I was wondering: 

Does the same apply to p9p as well or is the entire codebase still governed by the Lucent Public License, exclusively?

Personally, I'm a fan of the BSD3 but I don't suppose that's ever going to happen, is it?

**Comment by rsc** [comment]
The code here is distributed under the Lucent Public License. In some cases there is new code that I wrote from scratch post-Bell Labs and that is MIT-licensed (for example, lib9pclient), as noted by a COPYRIGHT file in the directory.

Nothing here is distributed under the GPL, nor is the Plan 9 distribution from plan9.bell-labs.com. Only the copy being distributed by Berkeley as part of the Akaros project is released under the GPL. If you want GPL'ed sources, obtaining them from [Akaros](http://akaros.cs.berkeley.edu/gitweb/?p=akaros.git;a=tree) is the way to go.
