### ISSUE TITLE
nbrecvul returns wrong error code

### ISSUE THREAD

**Issue by timnewsham** [9fans/plan9port#77]
The man page (https://swtch.com/plan9port/man/man3/thread.html)
implies that nbrecvul (aka channbrecvul) should return 0 if no
data is available, but the implementation returns (ulong)-1:

src/libthread/channel.c:409
ulong
channbrecvul(Channel *c)
{
    ulong val;

    if(_chanop(c, CHANRCV, &val, 0) > 0)
        return val;
    return -1;
}

I imagine the fix is just to make it return 0 instead of -1.

ref: https://groups.google.com/d/msg/plan9port-dev/sPV0kwMM68E/3fN3pNlgBAAJ

**Comment by 0intro** [comment]
The Plan 9 implementation of nbrecvul returns 0, so it matches the manual. There is an inconsistency in the plan9port implementation.

However, the return value of channbrecvul is notably used as the return value of the [needkey](https://github.com/9fans/plan9port/blob/5f6612b/src/cmd/auth/factotum/confirm.c#L129) and [badkey](https://github.com/9fans/plan9port/blob/5f6612b/src/cmd/auth/factotum/confirm.c#L140) functions from factotum.

When the needkey and badkey functions are used, their return value is compared to < 0 to handle the error case (for example [here](https://github.com/9fans/plan9port/blob/5f6612b/src/cmd/auth/factotum/key.c#L89)). So, if we fix the nbrecvul function, we should change the function calling nbrecvul as well.

**Comment by rsc** [comment]
Fixed this a few days ago to match Plan 9. 
Thanks for flagging needkey and badkey.
I rewrote them, although I don't understand how they are correct.
