### ISSUE TITLE
update website

### ISSUE THREAD

**Issue by josephholsten** [9fans/plan9port#79]
Is there a way to submit a change request for https://swtch.com/plan9port/?

I'd like to:
- change `browse`:`https://swtch.com/plan9port/` link to `code`:`https://github.com/9fans/plan9port`
- remove `hg`, `hgweb`
- rework download section

**Comment by sevan** [comment]
There's already a patch pending for commit
https://plan9port-review.googlesource.com/#/c/2880/

**Comment by josephholsten** [comment]
Awesome, anything I can do to expedite? Also, love the next avatar.

**Comment by sevan** [comment]
not sure what the process is, I guess a review of the changes is always good. Anything else that needs to be added??

**Comment by 0intro** [comment]
We moved the website to [9fans.github.io](https://9fans.github.io/). Consequently, you can send pull requests to the [9fans.github.io](https://github.com/9fans/9fans.github.io) repository on GitHub.

**Comment by josephholsten** [comment]
@0intro Yay!
