### ISSUE TITLE
compile failure on FreeBSD-11.0

### ISSUE THREAD

**Issue by karisawa** [9fans/plan9port#83]
Plan9port cannot be compiled on FreeBSD-11.0. (I use clang in 9c and 9l)
The problem is in src/cmd/auxstats/FreeBSD.c.
For the temporally, I replaced it by dummy code (DragonFly.c) but I want to know correct one.

**Comment by kdhp** [comment]
There is a patch for this in the FreeBSD ports tree:
https://svnweb.freebsd.org/ports/head/devel/plan9port/files/patch-src-cmd-auxstats-FreeBSD.c

**Comment by karisawa** [comment]
Thanks for the infomation.
I will try.

**Comment by karisawa** [comment]
Compilation is finished with that fix.
Thanks again.

**Comment by francisconti** [comment]
I believe this is fixed via commit da8a485fc143aa323845fafcf0f0f836c76a116b on Jan 17.
