### ISSUE TITLE
troff fonts have no HI and HB

### ISSUE THREAD

**Issue by realwhz** [9fans/plan9port#84]
troff reports error that it cannot open font file devutf/HI and devutf/HB.

I checked the directory plan9/troff/font/devutf and these two are missing.  The original Plan 9 from Bell-labs indeed has these.  Is there any reason why HI and HB are removed?  Should tmac be updated accordingly?  Thanks.

**Comment by rsc** [comment]
Looks like a bug. We should probably restore those. There have been problems in that directory with case-sensitive name collisions in the past but I don't see what those would have collided with.

**Comment by 0intro** [comment]
On Plan 9, the /sys/lib/troff/font/devutf directory contains HI, Hi, HB and Hb files.

**Comment by rsc** [comment]
OK, that's it then. I feel like maybe I intended to change the code to use different file names but never did.

**Comment by 0intro** [comment]
In fact, you renamed:

Hb → Helvetica-Narrow-Bold
Hi → Helvetica-Narrow-Oblique
Hr → Helvetica-Narrow:name
Hx → Helvetica-Narrow-BoldOblique

But you left HB, HI and HX out, probably because they were removed because of the case-insensitive file system.

I can add HB, HI and HX back if you want.

**Comment by rsc** [comment]
Sounds good thanks.
