### ISSUE TITLE
Acme: no to Upspin user names/folders

### ISSUE THREAD

**Issue by kristofer** [9fans/plan9port#89]
it appears that  u/foo@bar.com/ cannot be opened by right-click in acme? so it means you cannot browse Upspin mounts using acme… selecting the foo@bar.com/ and right click does nothing noticeable 

perhaps I have something wrong in p9p?

**Comment by KevinMGranger** [comment]
Is that directory already in your working dir and/or do you have a plumber rule for it?

**Comment by rsc** [comment]
The character class `a-zA-Z¡-￿0-9_/\-` appears many times in $PLAN9/plumb/basic. You will need to add @ to it to make right-clicks work.

**Comment by masiulaniec** [comment]
Acme's source code needs adjusting too because it fails also when not using plumber.

**Comment by rsc** [comment]
Fixed plumb rules. Use plumber.
