### ISSUE TITLE
Mac should use OpenBSD pty code 

### ISSUE THREAD

**Issue by spyffe** [9fans/plan9port#90]
On some Mac computers, the pty code currently used for Darwin does not find any ptys — they all return Resource temporarily unavailable.

Copying cmd/9term/OpenBSD.c to Darwin.c fixes this.

**Comment by jxy** [comment]
Yes.  The current code cannot find any ptys in High Sierra.

**Comment by 0intro** [comment]
Since which Mac OS X version did it started to fail with the current Darwin.c?

**Comment by jxy** [comment]
For me, it started to fail since I upgraded to High Sierra.

**Comment by mariusae** [comment]
@jxy and OpenBSD.c fixes this?

**Comment by jxy** [comment]
Yes.

**Comment by mennis** [comment]
I recently rebuilt on Sierra and it was fine.  High Sierra Release is where I saw the break. I didn't try the  High Sierra beta.

**Comment by nicoNaN** [comment]
On 10.13 here and confirm replacing `Darwin.c` with `OpenBSD.c`'s code and rebuilding works fine.
