### ISSUE TITLE
venti stats image generation issue on amd64 Linux

### ISSUE THREAD

**Issue by stroucki** [9fans/plan9port#91]
On migrating to 64 bit Linux from 32 bit, I noticed that the venti stats image graphs look corrupted when plan9 is compiled in a 64 bit environment.
It looks to me like the bit depth of the image is off; instead of the bottom of the graph starting at the bottom of the image, it is starting in the center, and the graph legends are aliased to illegibility, as if the final png conversion had to scale oversized data to the image dimensions requested. For example, look at this graph of the dcache hit rate:
```
http://localhost:8001/graph?arg=dcachehit&graph=pctdiff&arg2=dcachelookup&max=100&min=0&t0=-600&wid=300&ht=30&fill=10
```

**Comment by szhilkin** [comment]
Hi ! Post a screenshot please, not link. Thanks.

**Comment by stroucki** [comment]
![graph](https://user-images.githubusercontent.com/1933610/28473558-240ae946-6e13-11e7-997f-2cf9c3e7670f.png)
This is supposed to show icache hit rate.

**Comment by stroucki** [comment]
I think I got it - the mid '90s heresy that sizeof(int) == sizeof(long) == 32 continues to bite:
```
diff --git a/src/cmd/venti/srv/png.c b/src/cmd/venti/srv/png.c
index ca45641..8805ada 100644
--- a/src/cmd/venti/srv/png.c
+++ b/src/cmd/venti/srv/png.c
@@ -212,7 +212,7 @@ writepng(Hio *io, Memimage *m)
        /* image data */
        zr.dx = Dx(m->r);
        zr.dy = Dy(m->r);
-       zr.width = rgb->width * sizeof(ulong);
+       zr.width = rgb->width * sizeof(u32int);
        zr.data = rgb->data->bdata;
        zr.x = 0;
        zr.y = 0;
```
The graphs display correctly with this patch.

**Comment by stroucki** [comment]
And here's a sample:
![graph](https://user-images.githubusercontent.com/1933610/28483713-a3879290-6e3c-11e7-9f29-aedf1ccf3a27.png)

**Comment by 0intro** [comment]
This kind of issues happens because the plan9port code has been copied from Plan 9, which uses the LLP64 data model (where sizeof(ulong)==32), while most POSIX operating systems chose the LP64 data model.

Please send a patch to Gerrit. I'll apply it. Otherwise, I can do the patch myself if you prefer.

**Comment by stroucki** [comment]
Regardless of the data model, this is at the interface of arbitrary size C types and where defined size types are needed. "4" is probably better than "sizeof(u32int)" in this case.

Gerrit requires a google login, which I don't have. I've created pull request #92. Thanks for applying!

**Comment by 0intro** [comment]
Unfortunately, we don't use pull requests yet. However, I've uploaded your patch on Gerrit.

https://plan9port-review.googlesource.com/#/c/2980/

Let me know if it looks good to you.

**Comment by stroucki** [comment]
Thanks, looks good.

**Comment by 0intro** [comment]
The change is now merged. Thanks!
