### ISSUE TITLE
First steps after installing plan9port on linux?

### ISSUE THREAD

**Issue by roscp** [9fans/plan9port#97]
Hello:
I installed plan9port from archLINUX packages (https://www.archlinux.org/packages/community/x86_64/plan9port/).
I can start acme but I can't have shell in it for example.

1. should I start running a plan9 filesystem on my local-machine for other parts of plan9 ports to work correctly? HOW?
2. What should be done after install?
3. What tools do I have at my disposal after the plan9port install?
4. where would the config files for plan9 software be located at?
5. any information a new user to paln9 find useful?

thanks
@0intro ( for help)

**Comment by jinyangustc** [comment]
I begin to use acme recently. [Here is some information and config I collected from many places.](https://github.com/jinyangustc/plan9) Although I'm on a Mac, I think you can still find something useful. And suggestions are welcome!

**Comment by jinyangustc** [comment]
And here is what I put in my `.bashrc` (this snippet is copied from one of the blogs mentioned in my last comment). You may want to put this in your `.profile` or `.bash_profile` or `.bashrc`.
```
# plan9
export BROWSER='safari'
PLAN9=/usr/local/plan9
PATH=$PATH:$PLAN9/bin
PATH=$HOME/git/plan9/bin:$PATH

# Plumb files instead of starting new editor.
EDITOR=E
unset FCEDIT VISUAL

# Get rid of backspace characters in Unix man output.
PAGER=nobs
MANPAGER=nobs

# Default font for Plan 9 programs.
font=$PLAN9/font/lucsans/unicode.10.font

# Equivalent variables for rc(1).
home=$HOME
prompt=" $ "

# if you want to use rc instead of your shell within acme, uncomment the following line
# shell=rc

user=$USER

export \
    BROWSER\
    PLAN9\
    font\
    home\
    prompt\
    user\
    PAGER\
    MANPAGER
```

**Comment by elrzn** [comment]
You may want to setup fontsrv.

```
% cd $PLAN9/src/cmd/fontsrv
% mk install
% fontsrv -p .  # this will list all fonts available
```

Then you can start acme like this:

`acme -a -f /mnt/font/Monaco/14a/font $1`


You should check https://github.com/mariusae/gitfiles as well if you're working with git.

**Comment by dancrossnyc** [comment]
This is more a general request for help, and not so much a specific issue. Marking closed, as I believe the information requested has been disseminated.
